### ISSUE TITLE
plone.app.contenttypes IContentLeadImage ugly styles

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1012]
plone.app.contenttypes has IContentLeadImage, which works well for News Items:

![ileadimage_on_news_item_ok](https://cloud.githubusercontent.com/assets/170891/9929563/ca16e43c-5d2d-11e5-8d13-05f1c51bf1ee.png)

It doesn't look nice for Pages, for example. But also for other content types:

![ileadimage_on_page_broken](https://cloud.githubusercontent.com/assets/170891/9929569/dcc93f30-5d2d-11e5-82a4-310434e731fe.png)

Also, it doesn't look nice for the ``summary_view``:

![ileadimage_on_summary_view_broken](https://cloud.githubusercontent.com/assets/170891/9929571/e7229e5e-5d2d-11e5-9520-efffa293ab62.png)

**Comment by sneridagh** [comment]
https://github.com/plone/plone.app.contenttypes/pull/269 Fixes it and make the use of the behavior consistent everywhere.

**Comment by thet** [comment]
Great! Does it also fix the summary_view ?

**Comment by sneridagh** [comment]
Whow! I forgot it! I will take care of it as well.

**Comment by thet** [comment]
Thank you! IMO that's a quite important task.

**Comment by sneridagh** [comment]
Fixed! This is how it finally looks. I've got rid of floating the image on the right. I've consensuated it with some people here and we felt that in the old version was somehow disconnected and lot of white space in between if you do not have description.
<img width="882" alt="screen shot 2015-09-18 at 14 33 16" src="https://cloud.githubusercontent.com/assets/486927/9959298/0e007150-5e13-11e5-9f36-98b0cbf0919e.png">

**Comment by thet** [comment]
Nice, thanks a lot!
The top position of the description isn't aligned with the top position of the image, but I can live with that.

**Comment by thet** [comment]
Sorry, forget that with the alignment. It is aligned, it's just the line height or whatever, which makes the text appear not in line with the image.

**Comment by davilima6** [comment]
-1 for left alignment, I think it's good images are aligned on the right. There's a differente in reading order: in left-to-right languages it's natural eye flow to have call-to-actions or other elements of interest (like a picture or callour) on the right. This enriches the layout of the existent elements. With left-alignment images are looken at less often because the eye only goes as far as the imaginary line of text.

Besides I don't think whitespace was a problem with previous Plone, at least I've never seen an issue around this. @agnogueira: what do you think?
