### ISSUE TITLE
Calendar portlet tooltip shows HTML

### ISSUE THREAD

**Issue by polyester** [plone/Products.CMFPlone#1046]
it should go through bootstrap-tooltip iirc, but it doesn't, or at least doesn't transform the HTML correctly

version: RC2/coredev

![screen shot 2016-02-25 at 9 07 14 am](https://cloud.githubusercontent.com/assets/31827/13321805/3cc58214-db9f-11e5-85bc-c70a4b13024c.png)

**Comment by pigeonflight** [comment]
Currently the title is set to html mark up
![image](https://cloud.githubusercontent.com/assets/31827/13321998/5b1d1578-dba0-11e5-9757-8289debb687d.png)

To fix this the following changes need to be made:
1. add data-toggle="tooltip" data-placement="top"  to the tag
2. replace the title with just the text related to the calendar event instead of having the markup in the title

**Comment by pakhandibaba** [comment]
https://github.com/plone/plone.app.event/pull/215

**Comment by pakhandibaba** [comment]
@pigeonflight please go through the PR.

**Comment by pigeonflight** [comment]
I just tested the PR and, it does remove the HTML, however, it seems to introduce a new bug. For my test I created an event that starts and ends on March 14, 2016. When I go to the calendar it presents as if the event occurs on multiple days. 

See animation:
![calendarfix](https://cloud.githubusercontent.com/assets/31827/13591539/9c9ee358-e4b7-11e5-9d11-3933db7804be.gif)

**Comment by thet** [comment]
Fixed via:
https://github.com/plone/plone.app.event/pull/241
and
https://github.com/plone/plone.app.event/pull/248
