### ISSUE TITLE
Screen jumps when selecting different field sets

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1061]
Plone 5.0.3 out of the box editing the front page:

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/341393/13571474/065b2892-e454-11e5-8b34-d69e6f951082.gif)

**Comment by abhibansal530** [comment]
Not able to reproduce.Which version are you using?

**Comment by hvelarde** [comment]
just upgrade to Plone 5.0.3 and this still happens.

**Comment by pigeonflight** [comment]
I was able to replicate this as follows:
- when the toolbar is at the top. 

It seems to jump when it is moving between shorter views that don't need a scrollbar and taller views that introduce a scrollbar.

The **dates tab** has no scrollbar because it is a shorter page
![image](https://cloud.githubusercontent.com/assets/31827/14056662/e8d8599e-f2bc-11e5-83fa-aa625695a691.png)

The **ownership tab** has a scrollbar because it is a taller page
![image](https://cloud.githubusercontent.com/assets/31827/14056682/39a0e35a-f2bd-11e5-9505-9af06e92bc15.png)

**Comment by hvelarde** [comment]
Seems to be fixed in Plone 5.0.4.
