### ISSUE TITLE
Invalid HTML because of wrong formatting of resource?version=datetimestamp

### ISSUE THREAD

**Issue by jladage** [plone/Products.CMFPlone#1086]
The datetimestamp has spaces.

A possible fix in CMFPlone.resources.browser.scripts.py

            if bundle.jscompilation:
                result.append({
                    'bundle': bundle_name,
                    'conditionalcomment': bundle.conditionalcomment,
                    'src': '%s/%s?version=%s' % (
                        self.site_url, bundle.jscompilation,
                        bundle.last_compilation.replace(' ','-'))  <-- do a string replace here
                })

**Comment by mauritsvanrees** [comment]
For reference, https://validator.w3.org/ complains about that space:

Bad value `.../++plone++static/plone-legacy-compiled.css?version=2015-08-18 08:08:33.581682` for attribute href on element link: Illegal character in query: not a URL code point.

And: "Characters should be represented in NFC and spaces should be escaped as `%20`."

Maybe add a `T` instead of a space in the datetime part, although I guess there might be a space in other parts.

**Comment by mauritsvanrees** [comment]
This was fixed in October by this commit: 67bb341a558c7ec1ffc65ebba3f5eecb5897fc79
