### ISSUE TITLE
Width of navigation portlet on mobile

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1101]
Would it make sense to increase the width of the navigation portlet on small display sizes (iPhone 6S in this case)?

![img_0070](https://cloud.githubusercontent.com/assets/594239/10123876/5ed16e02-6545-11e5-8ac5-e7d7847b30b0.jpg)

**Comment by thet** [comment]
The navigation portlet takes too much space away, which should be reserved for displaying the content. Wouldn't it be better to hide it in a slide-in menu and displaying it only when the user wants to?

**Comment by davilima6** [comment]
+1 on default full width for mobile: no reason to waste the right-side whitespace when nav items titles are oftenly larger than Plone's defaults (News, Events, Users), especially out of English domain.

@thet: That'd be interesting but wouldn't solve the same problem with other portlets (eg: collections might also display lengthier titles). Besides it'd also conflict with toolbar for right column portlets.

If there's design opposition to having full width columns on mobile maybe we could add a small handler into mobile's portlet header for expanding/contracting?

**Comment by thet** [comment]
i agree, the slide-in menu might not work well.

actually i think on mobile devices we should not split up the navigation into a portal section navigation and the navigation portlet. we should have them combined in the mobile menu.
besides of that, i think, different screen sizes also need different contents (e.g. instead of the portal sections and navigation menu one combined one) and also leaving out the less important information to reduce the payload (maybe hiding them within collapsible elements and load them dynamically). 

for other portlets, they should be displayed full width and below the main content on small screen sizes. this is a common way of layouting less important stuff for mobile devices.

**Comment by thet** [comment]
the short term solution might just be to display all portlets full width below the main content.

**Comment by thet** [comment]
no, other way around, sorry for my mess:
+1 for making portlets full width on small screen sizes in general.
+1 for hiding the whole left portlet column in a collapsible element (alternative: each portlet individually).
the right portlets column is already displayed below the main content area, so all is fine here.

**Comment by jensens** [comment]
meanwhile full width and works fine
