### ISSUE TITLE
CSS issue on "Pattern options" tab in Resource Registries

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#1111]
![resource-registry-css-bug](https://cloud.githubusercontent.com/assets/191024/10175482/66a27dc8-66ef-11e5-88d7-2ef2ce171bb9.png)

**Comment by nikandroff** [comment]
Hello!
I took a look at this issue and it seems that I have found the problem.

It seems to me that there is a type at ```resourceregistry/pattern.resourceregistry.less``` file, line 93.
The style is attributed to a non-existent class `.patternoptionsuse` what is apparently a typo and has to be `.patternoptions`.
That is the reason why "pattern options" tab has the CSS issue: the padding style is not getting attributed there.

I would like to make a Pull Request for this issue. However, I am confused by the fact that changes in this .less file are not saved and applied after I relaunch Plone by `bin/plonectl fg`.

Could you advise how to see changes in my case?

**Comment by davilima6** [comment]
Hi, @nikandroff. This is inside the mockup package so first you have to install its dependencies. Get inside the directory you cloned the mockup repository to and type: `sudo apt-get installl phantom-js && make bootstrap`. After that you can generate the desired CSS files from the LESS ones using: `make bundle-resourceregistry` or `make bundles` for all bundles.

**Comment by newbazz** [comment]
Hey i would like to help something on this issue, can someone please elaborate it.

**Comment by vincentfretin** [comment]
This seems fixed in Plone 5.2.2. See screenshot, we have a `<div class="form col-md-12">` the `col-md-12` class provides a `float:left` that fixes the issue apparently. The parent `<div class="row">` already provides the `clear: both;`
![Capture d’écran de 2020-07-01 12-07-57](https://user-images.githubusercontent.com/112249/86232210-e84a6e00-bb93-11ea-8d3b-55ceb15dcaed.png)
But I did the fix in https://github.com/plone/mockup/pull/990 so the padding-top is the same as in Less variables tab. The changes will be picked up next time we do new bundles in plone.staticresources.
So with the rule applied this gives:
![Capture d’écran de 2020-07-01 12-32-13](https://user-images.githubusercontent.com/112249/86234278-f5b52780-bb96-11ea-93ae-4e4c74d83347.png)
