### ISSUE TITLE
Customise favicon TTW in same way as logo.

### ISSUE THREAD

**Issue by Robynstar** [plone/Products.CMFPlone#1122]
It would be very handy to also be able to upload a favicon in SIte Settings, alongside the logo. These are the two immediately-obvious places where Plone branding is visible and would want to be replaced with the client's branding.
Looking at these two pages:
http://caniuse.com/#feat=link-icon-svg
http://caniuse.com/#feat=link-icon-png
it might be worth having the FormHelp suggest only .ico or .png files.

This was very briefly mentioned in #165, but seemed to get left by the wayside.

**Comment by israel-lugo** [comment]
Is there any plan to implement this? I've just recently installed a Plone site and have been looking around as to where one might change the favico. So far I've tried the ZMI (creating a file in portal_skins/custom/favicon.ico but that did not help).

**Comment by fulv** [comment]
As I recently found out when I replaced the favicon on a site, there are now at least 7 different favicon files loaded in the `<head>` (some of which might actually be identical), some `.png`, some `.ico`.  Ideally, we should have a programmatic way to upload one image file and generate all the others, but I don't know if it's possible.
_Note:  this is not really Plone 5's fault, it's just the way modern websites do it nowadays.  In fact, I've seen sites with even more favicons._

**Comment by thet** [comment]
Uploading just one favicon would be ok, if it has a decent resolution and can be scaled from 128px or more down to 16pixels without quality compromises. If that's not possible or someone wants to have different icons for different devices/resolutions, you'd have to add as many as you need.

In a recent project we used a 128pixel version and let the browser scale it down as needed with only two ``<link>`` elements:
```
<link rel="icon" href="/++theme++mytheme/img/favicon.png" type="image/png">\
<link rel="apple-touch-icon" href="/++theme++mytheme/img/favicon.png">
```

That actually should be enough. I would avoid add more and more different icons for resolutions which may be outdated in a year anyways. I wouldn't use .ico also, because that's only to support old IE versions. Unfortunately SVG favicons are only supported by firefox and safari yet.
See: http://caniuse.com/#search=favicon

**Comment by Lmpessoa** [comment]
Although I'm in favour of a more centralised setting option for favicon close to the site logo, I'm a little bit sceptic this would be implemented since I found out I can set up a file at the root of a site with the same name of those expected in the HTML <head/> section and Plone will load those files instead the defaults. It is not much intuitive or easy to be done, but works.

**Comment by hvelarde** [comment]
> Note: this is not really Plone 5's fault, it's just the way modern websites do it nowadays. In fact, I've seen sites with even more favicons.

yes, @fulv, they call this "progress" ;)

in fact is a little bit more difficult to get this right; to get an idea check this site we use to validate our projects:

https://realfavicongenerator.net/favicon_checker?protocol=https&site=plone.org

I think we need to work on this at some point because I'm also tired of this madness.

**Comment by davisagli** [comment]
An option to set a custom favicon was added to the Site control panel in Plone 6.0.0a3
