### ISSUE TITLE
Plone legacy bundle: error loading javascripts!TypeError: define is not a function

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1133]
I am receiving the following error with xmldirector.plonecore on Plone 5.

The related JS initialization code was supposed to work with earlier betas.

https://github.com/xml-director/xmldirector.plonecore/blob/fs2/xmldirector/plonecore/browser/resources/local.js#L2-L20

I am still not getting the story how to write/register resources both for Plone 4.3 and 5.0.

![screenshot 2015-10-04 17 24 28](https://cloud.githubusercontent.com/assets/594239/10268545/da554536-6abc-11e5-89da-7905b14d590a.png)

![screenshot 2015-10-04 17 24 22](https://cloud.githubusercontent.com/assets/594239/10268546/def28ff4-6abc-11e5-9443-89f2034cf573.png)

**Comment by thet** [comment]
Looks like, this has something to do with the following pull-request: https://github.com/plone/Products.CMFPlone/pull/870/files
This unsets ``define`` and ``require`` for Javascripts, which are loaded in the **legacy bundle** (thus, registered to ``portal_javascript`` via ``jsregistry.xml`` in Plone 5).
The pull request was an answer to other problems with Javascript, e.g. the DataTables one, which tries to improperly register itself as an AMD module, if require.js is present (see issues: https://github.com/plone/Products.CMFPlone/issues/837 and https://github.com/plone/Products.CMFPlone/issues/845 ).

The error is about ``define`` not being available. Since I cannot see a reference to ``define`` in your script, maybe ace needs define?

In general I'd use two profiles - one for Plone 5 and one for Plone 4. In Plone 5, you register your Javascript to the new resource registry via ``registry.xml`` configuration. In Plone 4, you need to use the ``jsregistry.xml`` way. If you don't use plone.app.widgets in Plone 4, you don't have ``require`` and ``define`` available there too.

**Comment by zopyx** [comment]
I don't want to be picky but this feels as if the complete legacy bundle stuff is broken. Isn't the purpose of the legacy bundle implementation to support old-style registrations out of the box?

**Comment by zopyx** [comment]
So I create a Plone 5-only profile with the following registry.xml:

https://github.com/xml-director/xmldirector.plonecore/blob/plone5/xmldirector/plonecore/profiles/default-50/registry.xml

However this give me the following weird error (XML is valid of course) and the code is based on the documentation

http://docs.plone.org/adapt-and-extend/theming/resources.html


2015-10-05 12:59:25 ERROR Zope.SiteErrorLog 1444042765.030.663850416589 http://dev1.veit-schiele.de:12020/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 257, in __call__
  Module Products.CMFPlone.factory, line 115, in addPloneSite
  Module Products.GenericSetup.tool, line 374, in runAllImportStepsFromProfile
   - __traceback_info__: profile-xmldirector.plonecore:default
  Module Products.GenericSetup.tool, line 1268, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1113, in _doRunImportStep
   - __traceback_info__: plone.app.registry
  Module plone.app.registry.exportimport.handler, line 49, in importRegistry
  Module plone.app.registry.exportimport.handler, line 94, in importDocument
  Module plone.app.registry.exportimport.handler, line 320, in importRecords
  Module plone.app.registry.exportimport.handler, line 218, in importRecord
  Module plone.supermodel.utils, line 134, in elementToValue
  Module zope.schema._field, line 151, in fromUnicode
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 184, in _validate
  Module zope.schema._bootstrapfields, line 309, in _validate
  Module zope.schema._bootstrapfields, line 212, in _validate
ConstraintNotSatisfied:

**Comment by zopyx** [comment]
Apparently  <value key="js"> accepts only one element compared to the key=css counterpart....appears like a broken definition of the underlaying schema.

https://github.com/xml-director/xmldirector.plonecore/blob/plone5/xmldirector/plonecore/profiles/default-50/registry.xml

**Comment by vangheem** [comment]
It's really tricky. We keep trying to support old javascript that does or does not have requirejs support.

Your problem is that you're trying to mix requirejs javascript in without using requirejs.

I really hate how picky requirejs is about some of this stuff. It's really difficult to get this right for everyone. I don't actually have a great answer for you on this right now besides doing an ugly hack that looks for _old_require and _old_define. I believe ace is extra annoying.

Look what we have to do here: https://github.com/plone/mockup/blob/master/mockup/patterns/texteditor/pattern.js#L86 in order to deal with ace loading issues.

If your local.js I'd go back to not trying to work in b/w compatible require call and do straight jquery. The tricky part for you is making it work on plone 4 also I assume so you can't use the ace that is shipped with Plone 5.

Best way for you is to just pre-build all the javascript you ship so you don't have to monkey with all these plone 4/5, requirejs/no-requirejs nonsense. There are multiple build tools you can use(grunt, gulp). Sigh, another JavaScript rabbit trail.

I really freaking hate JavaScript sometimes...

**Comment by zopyx** [comment]
I removed all require.js related stuff again...

https://github.com/xml-director/xmldirector.plonecore/blob/plone5/xmldirector/plonecore/profiles/default-50/registry.xml

https://github.com/xml-director/xmldirector.plonecore/blob/plone5/xmldirector/plonecore/browser/resources/local.js
