### ISSUE TITLE
RFC/Idea: "Export" Button for any settings page

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#1137]
Use-Case: Joe created a Plone site and uses the control panel to adjust the settings. 

At one point Joe wants to move the settings made to a `registry.xml` file. 

Exporting all settings is too much, Joe wants only the language control-panel, and the site-controlpanel form to be exported.

Joe navigates to the language controlpanel. At the bottom theres a button "export this settings". Pressing this button opens a textarea with the xml of the settings.

Nice-to have: Import settings using the textarea.

**Comment by tisto** [comment]
+1

**Comment by gforcada** [comment]
As a bonus I would add that only the changed settings should be exported

**Comment by jensens** [comment]
Technically this all could be more difficult than it seems. GenericSetup is a dino. But I currently have no time to dig deeper, so I probably dont know all possibilities

**Comment by idgserpro** [comment]
I think this needs more discussion, from a Plone roadmap perspective:

Is this option to "Site Administrators" or "Managers"? Are we going to give "Site Administrators" export capabilities? How useful is this option to them if the "Site Administrator" can't *import* the xml himself? 

In my opinion, if Joe still needs to give this registry.xml to another integrator to upload "only this information" in a policy product, I don't see any advantage adding an export option to controlpanel. He just need to ask for the integrator "I need only language and site controlpanel settings". Giving the export option without import to "Site Administrators" we will not solve the problem of the integrator but now we need more code (and more tests) to do something we already have at ZMI that the integrator already has to use.

If you decide to go by this approach, I think it sould be the simplest one, and it shouldn't add a textarea like you're suggesting: it should export the settings like ```@@dexterity-types``` does for it's types. It will be a button that just automatically downloads the xml.

**Comment by jensens** [comment]
This ticket is a bunch of ideas, so its intention was to start a discussion. The current situation to get/ pull registry settings out of a running plone is via ``portal_setup`` and dump the whole registry. This is not usable/ acceptable and wastes time. Also nobody loves to write XML manually. So I try to summarize.

Export:
- For each control-panel 
- Only changed values/ non-defaults (currently: all values)
- Only value itself, not the field definition with title etc. (currently included)
- Which roles: manager or site administrator?
- As download (similar to dexterity) or as textarea/ace (more convenient for copy-paste), maybe as popover?
- Button placement for export similar to dexterity (keep UX).

Import:
- Do we need this? Need more opinions here. "Hackable Plone" approach? What do others thing?
- Which roles: Manager or Site Administrator?
- By file upload or using a textarea/ace?

**Comment by djay** [comment]
it's better to change the ticket title to not "lead" the solution. the problem you want to solve is "how to easily move settings from one site to another".

Personally I'd prefer a solution inline with what @datakurre implemented. Where settings are stored in a theme and can be imported on theme activation or manually. You can edit them using the editor TTW if you want to refine them. You could also export them into a theme. Once in the theme you can upload or download as a zip file. If you don't want have your setting and theme in the same file, then its fine, create a new empty theme just for your settings and snapshot your selected settings into that. I hate how our settings are all in different places. I want to centrally deploy a whole site configuration, theme, settings, scripts and default content from a single theme zip.

**Comment by jean** [comment]
I would be concerned about missing settings. I.e. Joe has to remember to export each control-panel where he made relevant changes. Also, maybe not _all_ his changes in each panel are relevant. Maybe there could be an `about:config` kind of listing of all settings, with non-default settings highlighted and (de)selectable.

**Comment by idgserpro** [comment]
I think the main motivation of this issue is because an exported ```registry.xml``` from a vanilla Plone 5 installation gives us **12551 lines**. Indeed, this is a lot of information, and since the navigation hierarchy is made per record *name* instead of record *interface*, it's really cumbersome to get what you want. Records from the same interface are all over this > 700kb xml.

But if this option is not going to be made available to "Site Administrators", I think the effort of adding all this code (and tests) to the whole plone controlpanel isn't worth. I know editing this xml is cumbersome, but in 10 minutes as an integrator I can open a xml in Vim and get all the information I want persisted in a policy. I can even keep a registry.xml in version control for each time I was asked to integrate settings into the policy and just do a diff to simplify all the process.

Being the cumbersome edition of this xml behemoth the main motivation of this issue, my 0.02c would be to have an export in portal_setup that gives me this instead of a single registry.xml:

```
profiles/
└── default/
    └── registry/
        ├── (...)
        ├── Products.CMFPlone.interfaces.controlpanel.IFilterSchema.xml
        ├── Products.CMFPlone.interfaces.controlpanel.INavigationSchema.xml
        └── Products.CMFPlone.interfaces.controlpanel.ISiteSchema.xml
```

So, all records are separated by their interfaces.  And we can have the same button to export in a specific controlpanel like we have in Dexterity, to export just what we want.

But now we have some problems with this approach: what do we do with registry.xml itself? Keep it for backwards compatibility? If I have the same record in registry.xml and in an interface xml like Products.CMFPlone.interfaces.controlpanel.ISiteSchema.xml, how do I handle it? Just raise an exception? IIRC, we have only an interface per each controlpanel, but is that really true?

**Comment by jensens** [comment]
fyi I sketched an exporter for single ``<records>`` by prefix here https://github.com/plone/Products.CMFPlone/commit/3a848fec71348cb9c0115a539fc7ad0e887f7562
Its just a short study to show its technical not very difficult.

**Comment by jensens** [comment]
in fact we have this
