### ISSUE TITLE
404 error with plonejsi18n

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1140]
I am getting this error while adding a  XML Director "Connector" (https://github.com/xml-director/xmldirector.plonecore, plone5 branch) to a fresh Plone instance

![out](https://cloud.githubusercontent.com/assets/594239/10301008/3d641eda-6bfe-11e5-9500-e29a845b9bfe.png)

**Comment by hvelarde** [comment]
possibly related with #949

**Comment by esoth** [comment]
I'm seeing this same issue with 5.0. Note that it is calling "plonejsi18n" on the domain root, instead of inside the portal.

**Comment by pigeonflight** [comment]
Is there a workaround for this?

**Comment by GerardRodes** [comment]
Fixed it adding "data-i18ncatalogurl python:portal_url + '/plonejsi18n'" to body tal:attributes.
Seems some js is adding the attr, but before resourceregistry-compiled.js and plone-compiled.js.

**Comment by sunew** [comment]
@zopyx I cannot reproduce on a 5.1.x  site - can you?

**Comment by zopyx** [comment]
I can still reproduce this error on Plone 5.1.4

**Comment by cekk** [comment]
I know that i'm late on this, but I always have that error on a 5.1.x Plone site when developing or when i expose the site id in the url.

The problem seems related to something that calls translations for "widgets" domain when the dom isn't loaded yet and the js doesn't find data-i18ncatalogurl attribute.

I tried on a fresh 5.2 and it seems fixed but i don't know how/where.

**Comment by ale-rt** [comment]
Closed due to long inactivity. Sorry for not coming back on this. Meanwhile Plone 5.1 is not supported anymore. Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
