### ISSUE TITLE
empty toolbar is confusing

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#1158]
# User problem

In some circumstances the toolbar is empty such as in the site setup.
This can make you think there is a problem as it looks like it hasn't loaded yet.
# options
1. Have contents always visible.
2. Have a home button (maybe all the time anyway) (or have a `view` which takes you to home)
3. Have a "close site setup" which returns you to where you activated site setup
4. Have all the configlets in the toolbar
   - con: going to scroll for sure
5. have some kind of visual marker to show its deliberately empty.

**Comment by davilima6** [comment]
I disagree it seems broken/confusing, it just behaves like that for site admins and those people are expected to know toolbar exists to operate on content only, not on settings/configuration contexts. That's why I wouldn't go for a Contents icon either.

I'd first confirm with more people the problem does exist. If really necessary then I'd add a Return icon to toolbar or - maybe better - re-add the "Up to site setup" / "Back to site setup" link (not "Close" since it's not a modal) which was present in all previous Plone (lost in migration?).

**Comment by ale-rt** [comment]
Closed due to long inactivity. 
Please reopen if this is still relevant for Plone 5.2 or 6. You could check one of the demo sites: https://plone.org/what-is-plone/plone/try-plone
