### ISSUE TITLE
add an optional "Help" button on each page of a Plone site

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1222]
...controllable via a checkbox (maybe in the Site control panel) so a visitor can ask a question or report a problem with the Plone site. Similar to the "contact" portal_action but "Help" is a keyword people are likelier to be looking for. Or "Report a Problem"? (maybe make the text be configurable as well). 

For the UI, a common implementation is as a small tab on the side of the browser window that can slide out on mouseover.

Not sure how this could be generalized to allow reporting of a Plone bug (as opposed to a problem on the specific site's content, functionality, or theme).

Something to chew on for the @plone/ux-team and @svx !

**Comment by cdw9** [comment]
I've seen on Groundwire sites that they added a Site Help link in the user dropdown, and I've always liked this idea. It could link to a view that contains information on how users can get help.

**Comment by jensens** [comment]
@tkimnguyen is this a plip or just an idea? I suppose an idea.

**Comment by hvelarde** [comment]
too specific; this could be implemented as an add-on.

**Comment by jensens** [comment]
Agree

**Comment by tkimnguyen** [comment]
It was an idea. I don't agree with a toss-away of "can just be an add-on". Isn't one of our complaints about Drupal is that everything is an add-on but Plone comes with great functionality out of the box?

**Comment by tkimnguyen** [comment]
Anyone else from @plone/usability-team want to comment? Some further thoughts:

- what should be displayed if a user clicks on the button? A single page or form that is managed in the Site Setup? Use acquisition to determine which page's content should be displayed, e.g. look for a "help" page in the containing folder hierarchy. Some other kind of (configurable?) logic to determine what to show?

- a configurable label and description for the button

**Comment by davilima6** [comment]
It's not that everything should be an addon, but in this case I also think it might not pertain to core.
The idea of help based on context is great but the execution is probably out of hand because we don't have content chunks for each UI (as would be the case with Microsoft's contextual app helpers, think Word dialogs). It'd be very hard to maintain too.

The `Report a problem` feature is also interesting and we have it implemented for most government websites as a viewlet under content (just above tags). It links to a PFG living on site root (named `/relatar-erros`) which acquisition helps by filling the `Page URL` field already. Check it out http://www.brasil.gov.br/saude/2016/09/continenete-americano-e-declarado-livre-do-sarampo/relatar-erros (or any other news item).
