### ISSUE TITLE
Unable to add custom columns to folder_contents

### ISSUE THREAD

**Issue by displacedaussie** [plone/Products.CMFPlone#1278]
# User problem

As a integrator I modify all dexterity content types to include a new "External UID" metadata field that matches a UID in an external system. I add `external_uid` to the catalog as both an index and metadata, as I intend to use this field for search and listing pages. I then select this column so that it will appear whenever I look at `folder_contents`.

As a site administrator I want to hide some of the columns available in the contents UI to make it less confusing for my editors.
# Internal

The `folder_contents` view has a hard-coded list of [available](https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/__init__.py#L163) columns. The Pattern that builds the table in the `folder_contents` view only requests this [restricted set of attributes](https://github.com/plone/mockup/blob/master/mockup/patterns/structure/pattern.js#L52).

Currently plone.app.collections brings in the list of metadata columns but doesn't do any attempt to translate these into nice translated labels. If we use the same vocabulary we would go backwards in usability. 

It might be possible to reverse engineer a label from dexterity schema field labels. However some metadata fields aren't attributes so won't have corresponding fields in a schema somewhere.
# Options
1. Add some kind of registry for defining and handling extra columns
2. Extend the list of attributes to include all [metadata columns](https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/behaviors/collection.py#L25)
   - con: no easy way to get nice labels for them.
3. same as (2) but have a blacklist in the registry to hide certain columns.
4. Have an adapter to determine the available columns in a given context so ZCML can be used to produce an alternative vocabulary.
   - con: what happens when you switch folders? contents doesn't currently adjust its columns per folder.

**Comment by gforcada** [comment]
:+1:

**Comment by miohtama** [comment]
I just want to present a third alternative:

* Make folder_contents view easily extensible - you can subclass or override the parts of template easily, namely have a `getAvailableColumns()` methdod which your subclass can override

* Override `folder_contents` view for selected content types using ZCML view registration mechanism. The site integrator can override the view for particular folder type or for the default folder type.

This way one can avoid the problem of creating new registration entries. In fact one can do this already by overriding `get_options()` but due to bad code structuring you end up manually copy-pasting a lot of irrelevant code to your subclass which you then need to keep in sync with upcoming Plone versions.

**Comment by djay** [comment]
This is for plone 5.  All those views are gone. Its now a bunch of js
without any flexibility on columns.
