### ISSUE TITLE
Request / Suggestion - Theming Related

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1337]
Plone 5 related
Request some experience themers to write good documentation on how to make very simple changes to the variables in the default barceloneta theme. for example simple things like how to include a new google font. how to change the font sizes, colors, altenatives to the use of colors etc

please do not delay this aspect

**Comment by djay** [comment]
@sudhan77 this issue is about documentation not the core product so needs to be raised in https://github.com/plone/documentation/issues. If you could provide more details of what you tried to do and the aspects of the existing manual that you tried to use and didn't help you, that would be good. 
I'll close this issue here.
