### ISSUE TITLE
PLIP: Add Archetype-style getters and setters to all fields on default content types

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1362]
## Abstract
Archetypes-based content types have some methods generated automatically that allow programmers to get and set fields' values programmatically. In Dexterity this is not needed as you can easily get and set values just by accessing the field attribute, which is nicer and more pythonic.

The addition of Dexterity as our default content types framework in Plone 5 had the unintended consequence of breaking a lot of code that depended on this Archetypes feature. That means code in many add-on has to be refactored, sometimes in nasty and repetitive ways, in order to achieve compatibility with plone.app.contenttypes and Plone 5.

Work on this has shown the process will lead to an enormous waste of time and resources if we don't offer an alternative on the core.

## Motivation
To speed up development and make it easier to get add-ons compatible with Plone 5.

## Proposal & Implementation
The proposal is to add getters and setters to all fields on default content types implemented in plone.app.contenttypes; method names must match the ones in Archetypes' version and could differ from actual field names as is the case in plone.app.event.

The best way to implement this still has to be discussed; IMO the implementation must be done in the same place that is located current code that enables this feature for title and description fields (probably plone.app.dexterity or plone.dexterity), but some Framework Team members think that we must implement the solution as an optional behavior in plone.app.contenttypes.

In the past we did some similar work for other features as in the case of the Collection content type.

This proposal has to be implemented in both, Plone 4 and Plone 5.

## Deliverables
A new version of plone.app.contenttypes (and/or other packages) with this feature. Documentation on how to use it, if needed.

## Risks
I don't see any.

## Participants
@hvelarde
@rodfersou

**Comment by hvelarde** [comment]
supersedes https://github.com/plone/plone.app.contenttypes/issues/318

**Comment by hvelarde** [comment]
@plone/framework-team any feedback on this? right now we have time but I don't know in a couple of weeks.

**Comment by jensens** [comment]
@hvelarde next FWT meeting is scheduled for tomorrow Feb. 16th. Thats the place and time where discussion about PLIPs happen. Stay tuned.

**Comment by datakurre** [comment]
To continue discussion from https://github.com/plone/plone.app.contenttypes/issues/318, -1 for this in dexterity, but ok in p.a.contenttypes or with some optional wrapper.

DX classes should follow their interface definitions. DX base classes implement mutable dublincore and therefore have setters and getters as required by the interface. For PAC types, most fields are defined in behaviors and therefore setters and getters should IMHO be defined in behavior interfaces and implemented by behavior adapters. It does have discoverybility issues, but is an issue by design with PAC. Yet, it would be acceptable to make PAC base classes to implement some compatibility interfaces with Archetypes.

There are issues in that DX is different from Archetypes and, in the worst cases, safe setter code for some fields are hidden deep in z3c.form adapters (blobs, relations, p.a.event fields), but there must be better way to fix it than bloating core DX objects. Also, Archetypes setters and getters were not only simple helpers, but also provided abstraction for alternative storage strategies. IMHO we should remember why DX exists in the first place and not make it a lesser copy of Archetypes.

**Comment by jensens** [comment]
FYI: frameworkteam meeting minutes here: https://community.plone.org/t/framework-team-meeting-minutes-2016-02-16/1596/1

**Comment by hvelarde** [comment]
> * more difficult than it seems, i.e. NamedBlobFile, ClassGen does not fit here. Manual work.
> * Could be implemented as an addon (i.e. using Events) or on initialization.
> * Risky, because methods appear everywhere, may break current addons.

could you guys explain a little bit these concerns?

**Comment by ebrehault** [comment]
I have detailed my position in https://github.com/plone/plone.app.contenttypes/issues/318#issuecomment-178640000
My opinion on this PLIP is:
- it does not address enough use cases to be in core,
- turning it into an add-on will not make it less efficient for the targeted use cases.

So my recommandation was just to make an add-on.

**Comment by hvelarde** [comment]
thanks for your time, guys!
