### ISSUE TITLE
portal_controlpanel/manage_editActionsForm permissions lost on saving

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#1376]
When I go to `MYSITE/portal_controlpanel/manage_editActionsForm` - the ZMI portal_controlpanels form - and click on save, the permissions of all configlets are set to "(none)".
This makes it impossible to edit something here.

**Comment by mauritsvanrees** [comment]
This works fine in Plone 4.3, but fails in 5.0. After saving, the `permissions` property of an action is no longer a tuple, but a string. We always take `permissions[0]`, so instead of `Manage portal` we now only get `M`.

Oops, that was me in commit af2bdc30ef. That was just a pyflakes/pep8 commit, but I managed to negate some condition checks... I will fix.
