### ISSUE TITLE
PLIP: Merge Products.RedirectionTool into core

### ISSUE THREAD

**Issue by vangheem** [plone/Products.CMFPlone#1486]
## Abstract

Allow users to manage redirects on their site and aliases to content.
## Motivation

Managing aliases and redirects on your site is a very important feature that should be handled OOTB.
## Proposal & Implementation
- merge Products.RedirectionTool into Products.CMFPlone
- improve control panel view to allow for paging(sites with many redirects make this page unusable otherwise)
- move the top-level toolbar entry to the "Actions" menu.
## Deliverables
- a PR with the feature merged into Products.CMFPlone
## Risks
- Current use of the word "Alias" in redirection tool is confusing. 
- Current redirectiontool doesn't warn when previous redirections have been replaced by other content and will no longer work
- <s>Current toplevel toolbar item adds extra noise to the toolbar.</s>

**Comment by hvelarde** [comment]
+1

**Comment by djay** [comment]
yes please. I added a risk about "Current use of the word "Alias" in redirection tool is confusing". Most of my users when asking for this talk about creating short urls, extra urls, alternative urls for content.

Also I suspect the UI for this could be combined with the UI for adjusting the shortname. Currently the UI for changing the short-name is buried in rename, which is also not that intuitive. It makes sense if you get the folder metaphor, but people coming at CMS from a public website point of view are thinking of adjusting their urls.

**Comment by gforcada** [comment]
An extra bonus for me would be to be able to create external redirects from within the control panel, so this way our marketing team could handle that from a central place. Right now, although external URLs are supported, they can not be created TTW.

**Comment by datakurre** [comment]
:+1: and :+1: for @gforcada's addition

**Comment by ebrehault** [comment]
I think "Current toplevel toolbar item adds extra noise to the toolbar" should not be listed as a risk. It should be part of the changes we need to implement in order to merge it in core. I update the PLIP accordingly.

**Comment by thet** [comment]
@gforcada in another project I'm using the Plone Link content type for external redirects, where I used nginx or apache redirects before. If you mean that.
However, +1 for this PLIP.

**Comment by gforcada** [comment]
@thet yes I know, but my use case is more about bulk updates rather than one at a time. So having an overview where to see all redirects and being able to upload a mapping that creates them automatically would be a real time saver for us.

**Comment by ebrehault** [comment]
The PLIP has been approved. See https://community.plone.org/t/framework-team-meeting-minutes-2016-04-12/1943

**Comment by fredvd** [comment]
There is a usability issue with exposing/managing the redirection storage to end users which I seen a few times in the past, curious if others have the same experience. Or did this already change in Plone 5?

There is no distinction between manually added redirects by users and automatically added redirects when you move/rename content. In a large site you would want to clean up those automatic redirects after a certain period because they clutter te redirect list, sometimes also cause confusion, etc. 

But as soon as you open the redirects to end users there are also explicit redirects that you shouldn't delete or at least be able to distinguish from.

For me this is a reason not to install redirectiontool by default, only when users request it and I can explain this caveat. 

It would be great as a first step if the stored aliases/redirects would have a datetime atrribute and a label to indicate if the redirect as created automatically by the system or through redirectiontool by the user.

**Comment by tomgross** [comment]
I think rewriting the product might be the better option:
 - use a behavior instead of managed_types
 - remove all the deprecated stuff

Testing the product I found a severe usability problem:  If a redirect exists and another redirect is created with the same name no feedback is issued. I would expect a message: There is a redirect with this name/URL already. You have the following options: Use new redirect, Keep current redirect

**Comment by Rudd-O** [comment]
This is going to be so awesome.  Thank you folks!

**Comment by svx** [comment]
@staeff @datakurre 

Nice work ! Thanks !

Would you mind to update the docs too ?

Since there is some UI involved a robot test for screen-shots would be super duper excellent uber awesome !

Thanks a lot !!!!

**Comment by staeff** [comment]
Hi @svx,

thanks for the heads up! I had it on the list to document it. Question: I was skimming the docs to see where it would fit, but I did not find a place. I was looking for a section where all the other controlpanels are documented. Did I miss to find it? If not, any suggestions where to put it?

**Comment by svx** [comment]
@staeff good point !

When it get merged into CMFPlone it should go into the /docs dir of the repo.

Currently the /docs repo of CMFPlone is using 'old style' and not following best practices. 

IMHO it's time to change that :)

Long answer short  put into /docs of CMFPlone, and after that I will create a PR which cleans up /docs and moves files to places where they belong.

Later we will 'fetch' /docs and will place it under the other docs on docs.plone.org, IMHO this should go under 'working with content' 

@polyester what do you think ?

**Comment by datakurre** [comment]
@staeff Would you able to create a checklist of missing parts, and possibly also create a WIP pull request for this? Obviously we missed Plone 5.1, but maybe we could get this merged soon after 5.1 final is out.

**Comment by datakurre** [comment]
https://github.com/plone/Products.CMFPlone/commits/plip-1486-redirection

**Comment by svx** [comment]
@staeff @datakurre is there something I can help with ?

I really need/want that thing  :)

**Comment by staeff** [comment]
@svx @dataflake I have to apologize, I am the bottle neck here. I will give an update on the state of the work and make a WIP pr this weekend.

**Comment by staeff** [comment]
@svx @datakurre I made a WIP pull request now. There are some tiny things that could be improved, as I see it. I'd be glad to get your opinions and questions.

**Comment by staeff** [comment]
@svx here is a list of things, that are needed or would be nice to have from my perspective. 

* @@redirection-controlpanel (global alias managment) must be reachable through the @@overview-controlpanel 
* @@manage-aliases (alias management on an object) should be reachable from a content type. Suggested solution is the make it an action (that is hidden by default)
* Confirmation dialogue when aliases are deleted
* Translations are needed
* User docs for the control-panel (https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-314412772)

This is one is needed for der Freitag:
* Add capability to add an external URL (p.a.redirector supports this)

**Comment by svx** [comment]
@staeff I can take care of the docs, no problem :)

**Comment by djay** [comment]
Was there any update on changing the word alias? I see no reference to this change.

**Comment by djay** [comment]
call it "url management".

**Comment by staeff** [comment]
@djay okay.

**Comment by djay** [comment]
One other UX issue is around alternate urls that no longer work because a new item has been created at that url. This can be very confusing and hard to work out.  Worse is when urls won't work due to acquisition. e.g. /plone. The control panel should probably warn the user redirections are ineffective as no 404 event gets generated. Possibly this is new feature after the merge?

**Comment by mauritsvanrees** [comment]
I am looking at this during the Alpine City Sprint 2019.

The current `Products.RedirectionTool` has a list of types for which redirects can be created. Looks like this is true for both automatic and manual redirects. The only place where this is checked, is in [`plone.app.redirector`](https://github.com/plone/plone.app.redirector/blob/1.3.7/plone/app/redirector/subscribers.py#L32-L38).
In the CMFPlone plip branch, this has been taken over, in the new `redirection_manageable_types` setting in the Types control panel. (BTW, this would need a change in plone.app.redirector to look at the new setting.)

But do we really need/want this? Does it make sense to only create (automatic) redirects for some types?
Danger is now that someone installs an add-on with a content type (or creates a Dexterity CT TTW), and forgets to update this setting, and then no redirects will ever get created for this CT.

I could imagine that we use this setting to determine on which content items we show the manage-aliases action.
Or add a boolean setting `filter_redirection_types`, default False, that determines whether we look at the `redirection_manageable_types` setting at all.

To get this PLIP moving forward fast, I suggest that I remove the `redirection_manageable_types` setting. This also means we don't need an upgrade step for this setting.

[I thought I had submitted this comment yesterday, but apparently not.]

**Comment by fredvd** [comment]
> But do we really need/want this? Does it make sense to only create (automatic) redirects for some types? Danger is now that someone installs an add-on with a content type (or creates a Dexterity CT TTW), and forgets to update this setting, and then no redirects will ever get created for this CT.

@mauritsvanrees for collective.restrictportlets this was I think the reason we created the logic to 'hide' portlets in a block list instead of creating an allow.  When new portlets are registered it will be an proactive task to also hide them. The same could be done for redirection_types.

**Comment by fredvd** [comment]
Maybe this is not the right place and it should also be listed as a feature after merge, but there is a real risk for 'big' portal sites in the long run.  They have been using the RedirectionTool for years and noticed that the redirection list got so big that the @@aliases-controlpanel whould just crash ( (100.550, aliases, 17Mb datastructure). So they created custom import/export tools and disabled the UI.

**Comment by mauritsvanrees** [comment]
@fredvd The crashing aliases controlpanel has been addressed by @staeff by adding batching. I improved it a bit yesterday. I actually added a million aliases and this takes a while to create, but the controlpanel still renders pretty fast after that.

**Comment by mauritsvanrees** [comment]
> for collective.restrictportlets this was I think the reason we created the logic to 'hide' portlets in a block list instead of creating an allow. When new portlets are registered it will be an proactive task to also hide them. The same could be done for redirection_types.

I have removed the unused `redirection_manageable_types` setting for now.

**Comment by mauritsvanrees** [comment]
I have updated the [PLIP config](https://github.com/plone/buildout.coredev/blob/5.2/plips/plip-1486-redirection.cfg) and requested PLIP jobs, and they have just been started:

- https://jenkins.plone.org/view/PLIPs/job/plip-1486-redirection-2.7/
- https://jenkins.plone.org/view/PLIPs/job/plip-1486-redirection-3.6/
- https://jenkins.plone.org/view/PLIPs/job/plip-1486-redirection-3.7/

I am still making changes, but the most important stuff has been done.

**Comment by mauritsvanrees** [comment]
And the PLIP jobs pass!
Some more changes coming in, but okay.

**Comment by mauritsvanrees** [comment]
I'd say this is ready for review. @plone/framework-team go ahead!

I have addressed most of the issues raised above, and a few I saw myself. Let me make a list of those, including the changes by @staeff, and the most important differences with the old RedirectionTool.

- Instead of 'alias' I use the term '**alternative url**'. The control panel and the context action are called 'URL Management'.
- The control panel uses **paging/batching**, so it no longer chokes when there are hundreds of thousands of redirects.
- In the control panel you can add **external redirects**. Only `https` and `http` are allowed.
- There is **no portal tool**, only a control panel and a browser view.
- In `plone.app.upgrade` I have an **upgrade** step that gets rid of the stuff the old RedirectionTool left behind. (I need to check this more thoroughly though.) The new settings (rolemap, controlpanel, actions) are set.
- There is **no longer a whitelist** of managed types. The related code in `plone.app.redirector` that checked this, is removed. If we want something like that, a blacklist would seem to be better.
- When adding an alternative url, if this **alternative already exists** or if there is existing content on this path, we give an error and don't add it.
- Same when the new alternative url is a path that can be **traversed** to, for example `/view`, or when it contains `@@`: this gives an error.
- The URL Management page for a single content item is no longer a tab, but is in `portal_actions/object_buttons`, so in the **actions dropdown**.
- The controlpanel is protected by the '**Manage Portal Aliases**' permission, granted to Manager and Site Administrator.
- The context action is protected by the '**Manage Context Aliases**' permission, granted to Manager and Site Administrator, Owner and Editor.

TODO:

- [ ] Add a few more tests. Preferably a robot test with screen shot to include in the docs.

Some remaining items are **wishlist** or **out of scope** for this PLIP, at least if we want this accepted and merged soon:

- [ ] Make distinction between **manual** and automatic redirects. And/or **datetime**. Should be possible, but may be tricky. This mainly needs changes in `plone.app.redirector`. I have some ideas for that. If this is not done, and you don't want to allow adding any alternative urls manually, then you can either hide the control panel and the context action, or disallow the two permissions.
- [ ] **Confirmation** dialogue when aliases are deleted. @staeff [mentioned](https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-356359681) this, but I am not in favour of this.
- [ ] Button to **export** the alternative urls.
- [ ] Button to **remove all** alternative urls, or all alternative urls that match the path prefix.
- [ ] Button to **check all** existing redirects, cleaning up bad ones.
- [ ] **Remove** existing alternative url when new content is created at this path. Mentioned by [@djay](https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-453371710) above. Could be done with a subscriber in `plone.app.redirector`.
- [ ] **Blacklist** of managed types.

**Comment by mauritsvanrees** [comment]
@svx You offered to help with the docs. You mentioned putting it in `Products.CMFPlone/docs` but there is hardly anything related there anymore.
I have some text for documentation:

--------------

**URL Management**

New in Plone 5.2 is the *URL Management* control panel and content action.
This is an adaptation of the Products.RedirectionTool add-on.
Since many years, if you move or rename a content item, Plone automatically makes a note of this.
When a user visits the old url, Plone redirects to the new url.

What is new in 5.2, is that you can manage these alternative urls.
You can view them, remove them, and add new ones.

In the Site Setup you can see the new *URL Management* control panel where you can do all this, including bulk upload of alternative urls.
As Editor, you can see a *URL Management* link in the actions menu of a content item, and add or remove alternative urls for this specific content item.

**Migrating from RedirectionTool**

The Products.RedirectionTool add-on is no longer needed in Plone 5.2.
You can either uninstall it before upgrading to Plone 5.2, or remove the product from the eggs and let the upgrade code from Plone remove it.
Any alternative urls (aliases) that you have added manually, will be kept.

Note: In the add-on you could specify the content types for which redirections could be made, but this is no longer supported.

**Comment by mauritsvanrees** [comment]
In the list of [changed items](https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-461636459) I forgot one thing. I have edited the comment to add it, but let me list it here for clarity:

- When you use the URL Management content action in a **navigation root**, the path of the navigation root is included. For example you are in  `/Plone/navroot/content` and you add alternative url `/foo` then this is added at `/Plone/navroot/foo`.

**Comment by jensens** [comment]
Framework team decided it is ready for merge.

**Comment by mauritsvanrees** [comment]
Thanks!
There are changes in two other packages besides CMFPlone. They were in the PLIP jobs, which were passing, but I didn't yet create pull requests for them.
I now did.  The changes are isolated, so the PRs can be merged separately:

- [ ] https://github.com/plone/plone.app.redirector/pull/10
- [ ] https://github.com/plone/plone.app.upgrade/pull/196

Will you merge them or shall I?

**Comment by jensens** [comment]
well, sure, I need to add checklist on my own before merge next time.

**Comment by mauritsvanrees** [comment]
Thanks! All is merged now.

It would still be useful to have feedback from Framework team or others on the items of the [wishlist](https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-461636459), whether they are indeed wished.  Most or all are relatively small, so may be fine for inclusion in the beta stage.

**Comment by jensens** [comment]
Ad wishlist: I don't see any value in making a distinction between manual/automatic redirects.

The proposed removal options are probably a nice to have. 

Export is for sure the most important on the list. Best in a format to be used as bulk upload. 

Allow/Deny list on based on Content Type is not how I would do it nowadays if this is needed. I'd rather add a behavior to be enabled/disabled on a type in order to switch the feature on or off. 

Confirmation dialogs are imo not needed. But proof me wrong here.

**Comment by fredvd** [comment]
@jensens the difference between automatic and manual redirects is one of the wishes of a very large university portal where the editors insert manual links to have shortcut-urls which have to   kept/preserved, but they would like to prune automatic (rename/move) redirects after a certain amount of time. They have/had the 100k+ redirects stored.

**Comment by jensens** [comment]
@fredvd ok, that's a use-case!

**Comment by pbauer** [comment]
🎉 Thanks for this! 
See it here in action: http://demo-latest-py3.plone.org/@@redirection-controlpanel
The future improvments suggested in the wishlist sound great too 😄

**Comment by djay** [comment]
It looks good but I can still see some users getting confused by it. A little more explanation on that page could help.

Specifically due to the way other CMS’s work some people still don’t realise you control the primary url of content by renaming content. They will likely end up in the control panel to try and do it here instead. 

Also it should mention that alternative urls result in redirections rather than content being available using both urls.
It should also warn that the redirection will only work while the alternative url results in a 404 not found so any future adding or renaming content might result in the alternative urls no longer working.

Perhaps?
```
URL Management
Add a new alternative url to redirect from. To change contents primary url use Actions > Rename.

Alternative url path (Required)
Enter the absolute path where the alternative url should exist. The path must start with ‘/‘. Only urls that results in a 404 not found page will result in a redirect occurring.
[                                   ]

Target Path (Required)
Enter the absolute path of the target. The path must start with ‘/‘. Target must exist or be an existing alternative url path to the target.
[                                   ]
```
