### ISSUE TITLE
Why do we have zc.buildout 1.7.1 in coredev for 4.3 branch, but UnifiedInstaller uses 2.5.0?

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#1502]
Isn't this confusing? @mauritsvanrees says in https://github.com/buildout/buildout/issues/99#issuecomment-204386089 that 1.7.1 is needed in 4.3.x because different version constraints can break the instance, but if UnifiedInstaller is using 2.5.0 and it's working, why can't both be 2.5.0? Why it works in UnifiedInstaller but not in coredev?

Motivated by https://github.com/plone/Installers-UnifiedInstaller/issues/40.

**Comment by mauritsvanrees** [comment]
Using zc.buildout 2.x should just work just fine, but I have seen too many times that updating a site to a newer buildout, and more so a newer setuptools, fails on an old sever. If you already have a `bin/buildout` script you are probably fine, but running bootstrap may fail.

The problem is often that there is a too old global setuptools (0.6) that needs to be upgraded first. Buildout will somehow try to update the global one and this fails. The global one may not be setuptools, but distribute, making this even harder.

If you update the global setuptools on a server, for which you need sudo rights, it might also cause problems in other buildouts that still use older versions.

Also, if we update the versions, then the user needs to use a newer `bootstrap.py` too.

When I encounter a problem like this on a server, I usually press onwards with zc.buildout 2 anyway and somehow fix it: with sudo upgrade setuptools (which may be from a system package, which is not nice to manually interfere with), or compile a new python, or create a virtualenv, and then it usually works. But it's a bit hard to come up with a good procedure that always works on every machine.

**Comment by idgserpro** [comment]
@mauritsvanrees the setuptools is already [20.1.1](https://github.com/plone/buildout.coredev/blob/4.3/versions.cfg#L31).

**Comment by idgserpro** [comment]
@esteele what is your opinion about this?

**Comment by idgserpro** [comment]
Since we will no longer have versions of Plone 4.3, it no longer makes sense.
