### ISSUE TITLE
how to get global definitions working after Plone 3 to Plone 4 upgrade

### ISSUE THREAD

**Issue by Farha14** [plone/Products.CMFPlone#1521]
Hi team,

We are planning to upgrade our plone from Plone 3.3.5 to plone 4.0. As per the step 'No more global definitions in templates' to upgrade the add -on product in https://plone.org/documentation/manual/upgrade-guide/version/upgrading-plone-3-x-to-4.0/updating-add-on-products-for-plone-4.0/no-more-global-definitions-in-templates.

global definitions of various variables are removed like template_id template/getId; normalizeString nocall:context/@@plone/normalizeString;. So if we are using these variables in out code what needs to be done?

**Comment by mauritsvanrees** [comment]
You need to add the definition yourself in each template that uses it.  So if a template uses the `template_id` variable you need to add this:

```
tal:define="template_id template/getId
```

That should probably be near the top of the file. But if you use it only once, you can define it near the line where you use it.

Since plone.org is scheduled to be refactored this year, let me point to the same page on docs.plone.org: http://docs.plone.org/4/en/manage/upgrading/version_specific_migration/p3x_to_p40_upgrade/updating_addons.html#no-more-global-definitions-in-templates
