### ISSUE TITLE
Plone 5.0.4: old-style css+jsregistry.xml files registered but not enabled

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1542]
I have a Plone 5 profile in xmldirector.plonecore with old-style registries for CSS:

https://github.com/xml-director/xmldirector.plonecore/tree/plone5-demo/xmldirector/plonecore/profiles/default-50

The CSS and JS files are properly registered with the plone-legacy bundle:

![screenshot-dev zopyx com 12020 2016-04-20 15-32-45](https://cloud.githubusercontent.com/assets/594239/14676460/c8f09b04-070d-11e6-92ae-2adf5eff1110.png)

However I need to enable develop mode first (in portal registry setting, select the "Plone Legacy" bundle
and click on save (with "develop CSS" + "develop JS" enabled). After this manual step my CSS/JS becomes active. However this should happen automatically...anything missing here?

**Comment by hvelarde** [comment]
seems the same issue reported in #1511 and already solved in #1515.

**Comment by jensens** [comment]
Whats the state here?

**Comment by cewing** [comment]
@jensens I can confirm that this is true.  The culprit appears to be this code from [Products.CMFPlone.resources.browser.resource.ResourceView.ordered_bundles_result](https://github.com/plone/Products.CMFPlone/blob/5.0.4/Products/CMFPlone/resources/browser/resource.py#L202-L205).

The list of bundles to process come from the `get_cooked_bundles` method of that same view.  It includes the `plone-legacy` bundle, which has `merge_with` set to `default`.  But when the process hits the test on line 202 in the highlighted section above, the test fails because `production` is set to `True`.  As far as I can tell, this prevents any bundles include in any way (including the `add_bundle_on_request` function from `Products.CMFPlone.resources`) from being included.  There appears to be no fall-back. 

In production it appears that the only bundles that will ever be included are `default` and `logged-in` although it does appear that if the bundle is registered with `merge_with` set to None, or no value, that would allow the bundle to be included. I'll try that next.

**Comment by cewing** [comment]
I can confirm that if the registry is *not* in development mode (`production` is `True`), and the legacy bundle is registered with `merge_with=None`, then the legacy bundle *is* included in requests.

**Comment by hvelarde** [comment]
as mentioned, above; this has already being solved and we're just waiting for the release.
