### ISSUE TITLE
Bug: Setting for "Link" in "Content Settings" Gets Unchecked

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#1547]
(Pv5.0) 
Site Setup > Content Settings > Link

If "Redirect immediately to link target" is checked (and saved), any changes to any other type, at any time, unchecks this selection.

**Comment by 3dogMcNeill** [comment]
Update: bug still present in 5.0.4. Possibly part of this, is that external links are not automatically redirected (when the box is checked), just internal links. This is particularly annoying when using a Plone site as an intranet.

**Comment by davilima6** [comment]
I confirm the bug in Plone 5.0.5 - and that it works right in 4.3.

**Comment by tmassman** [comment]
The bug was once fixed in p.a.controlpanel (https://github.com/plone/plone.app.controlpanel/commit/e290698278d10fa294fd6c3009507ea350096afd#diff-e7c4c9fdf3e0c0fce684dac5a93a9a3e), but when migrating the code to CMFPlone, this fix was not included (see https://github.com/plone/Products.CMFPlone/commit/f495a10db30b12f27ce846d9ed8157be5a53e7af). I don't know why this is missing, since the bugfix happened about 2 years before the code was migrated 🤔 

Applying the fix again will solve the problem, and needs to be done for all release branches.

**Comment by tmassman** [comment]
As it turns out this bug was already fixed in 5.1, but didn't make it into 5.2...

**Comment by tmassman** [comment]
Merged.
