### ISSUE TITLE
Image lost in TinyMCE after size of scale is changed

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1567]
TinyMCE uses the the unique url (@@images/2c30b49a-22d1-499c-ab31-b32a8af0951f.png) of a a calculated image scale for embeddding. 
If for example a scale is changed, the url/image does not exist anymore and therefore shows a missing image.

If we would use the image url in the format of @@images/image/preview, the image scale with TinyMCE would be recreated and shown.

**Comment by jensens** [comment]
Makes sense. Those UIDs are not meant to be stable, they are just a reference to a current version of a scale. If the image changes or something else changes the modified date of the Image type, the UID is invalid and a call to it leads to a 404. The correct permanent way to address image scales is ``@@images/fieldname/scalename``, i.e. ``@@images/image/mini``.

**Comment by agitator** [comment]
an upgrade step for existing installations would also be nice

**Comment by jensens** [comment]
For the records: the only case for using UIDs in the URL of image scales is when a scale is created on the fly, or iow w/o using predefined scales. This auto-generated scale URL must never be stored. It must be used only in generated pages, where the UID will be recreated when content was changed.

**Comment by agitator** [comment]
after some debugging...
Good thing is TinyMCE put the image with @@images/image/mini into the html.
Problem happens in #101 of TransformEngine.py in PortalTransforms where the result of the previous transform gets cached.

The problem will exist for the time defined within init via max_sec_in_cache=3600

Possible solution: make this configurable via a registry entry and set the default to 0

@plone/framework-team

**Comment by MrTango** [comment]
This UID-urls also leads to cached image in pages, even if someone has change the original image file in the image object. So the page which includes an image, is showing an old version of an image, which is painful in big sites. This is also the case in Plone4. If we can fix this, it would be great to have this fix also in Plone4.

**Comment by jensens** [comment]
From what I read from the code the UID scales are wiped at the moment the modified date of the content item has changed.

**Comment by frisi** [comment]
i digged a bit into this today (for Archetypes only).

PortalTransforms is storing transformed data onto BaseUnits (AT-fields) in a `_v_transform_cache`
attribute together with a timestamp the transformed text has been genereated.
there is no metadata like modificationdate of the document.
portaltransforms simply compares this timestamp with now and returns the cached data if the difference is less than one hour (3600 seconds is the default)

when does the transform cache gets invalidated?

the _v_transform_cache attribute is deleted by the _cacheExpire() method of BaseUnit which is called when a field's `update`, `setFileName` or `setContentType` method are called.


i set up a subscriber to modified events for ATImages that invalidates the portal_transform cache for the textfield of all objects that use this image (using p.a.linkintegrity).
this is no perfect solution (i.e one could search for all richtextfields and invalidate them) but a start:

```python
def image_updated(obj, event):
    """update textfield of documents that use this image
    see https://github.com/plone/Products.CMFPlone/issues/1567"""

    docs = obj.getBackReferences('isReferencing')
    for doc in docs:
        text_field = doc.getField('text')
        if text_field is not None:
            text_field.getBaseUnit(doc)._cacheExpire()
```

subscriber registration
```xml
  <subscriber
      for="Products.ATContentTypes.interfaces.image.IATImage
           Products.Archetypes.interfaces.IObjectEditedEvent"
      handler=".handlers.image_updated"/>

  <subscriber
      for="plone.app.imagecropping.at.IImageCroppingAT
           plone.app.imagecropping.events.CroppingInfoChangedEvent"
      handler=".handlers.image_updated"/>

  <subscriber
      for="plone.app.imagecropping.at.IImageCroppingAT
           plone.app.imagecropping.events.CroppingInfoRemovedEvent"
      handler=".handlers.image_updated"/>
```


this will make documents not show a broken image when users upload a different image file or change the cropping region with `plone.app.imagecropping`


what's missing is static-text-portlets.
they also use PortalTransforms for the html output.
portlet texts get invalidated when editing images (but not when chaning image scales with p.a.imagecropping)
don't know how / where these caches get invalidated


it should not be too hard to implement this for dexterity too.


for plone 5 one would use something like this instead of getBRefs('isReferencing'):
plone.app.linkintegrity.utils.hasIncomingLinks(img)
(see https://pypi.python.org/pypi/plone.app.linkintegrity/)

**Comment by petschki** [comment]
is this related to https://github.com/plone/plone.app.textfield/pull/30 or #2465 ?

**Comment by jensens** [comment]
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
