### ISSUE TITLE
Is viewlets.xml now mandatory for adding viewlets in Plone 5?

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#1586]
I have a really simple viewlet in an addon and its registration for `plone.app.layout.viewlets.interfaces.IPortalFooter` manager happens only at its configure.zcml (I don't have a profile in this addon, so no viewlets.xml). It works fine in Plone 4.3.x. You can do a `@@manage-viewlets` and check that it's there.

But now, in Plone 5.0.x, it doesn't show in `@@manage-viewlets`. Is the use of viewlets.xml now mandatory? Why? We don't have this information for Plone 5 in http://docs.plone.org/develop/plone/views/viewlets.html.

**Comment by ida** [comment]
It is mentioned in the docs, that using a profile-config is good practice, a little bit hidden in this chapter:
http://docs.plone.org/develop/plone/views/viewlets.html#creating-a-viewlet-manager
Would you like to improve the docs maybe? Easy as an PR :)

Otherwise to get rid of the viewlets-hassle at all, you could replace them with portlets, here's an example:
http://stackoverflow.com/questions/37163468/how-to-make-footer-to-show-items-from-main-menu-automatically-in-plone/37180542#37180542

And LBNL there's Mosaic on the rise, which promises to be a successor to viewlets and portlets.

**Comment by mauritsvanrees** [comment]
A `viewlets.xml` should not be needed, at least his would be unexpected for me. It is only needed if you want a specific order, or if you want to hide a viewlet.
Maybe the viewlet is defined for a specific theme, or a browser layer?
Can you show the zcml code where you are registering this viewlet?

**Comment by idgserpro** [comment]
> Maybe the viewlet is defined for a specific theme, or a browser layer?

Yep. Sorry about that.
