### ISSUE TITLE
image path in merged bundle not working?

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#1767]
Trying to update collective.medialementjs

css is registered at "++resource++collective.mediaelementjs/mediaelementplayer.css"
and contains for example the style "background: transparent url(controls.svg) no-repeat;"
available at http://localhost:8080/Plone/++resource++collective.mediaelementjs/controls.svg

When I merge the bundle with the default bundle, the path for the controls.svg is transformed to http://localhost:8080/Plone/++plone++production/++unique++2016-09-18T11:38:08.837701/++resource++collective.mediaelementjs/controls.svg
and therefore not found

@ebrehault any idea how to fix that?

**Comment by thet** [comment]
We use https://github.com/less/less-plugin-inline-urls in order to avoid such problems with images.
But that doesn't work with SVG images, though.

IMO, we need to fix this twice:

- We don't add the protocol and domain part, including path to the portal root in merged bundles
- We make the ++unique++ traverser be able to resolve the ++resource++ part of the url, but I guess, that's already the case.

+1 or this needing a solution.

**Comment by ebrehault** [comment]
This PR should have fixed it: https://github.com/plone/Products.CMFPlone/pull/1763
