### ISSUE TITLE
Newest LinguaPlone: Unauthorized access to default page with private state

### ISSUE THREAD

**Issue by mck9** [plone/Products.CMFPlone#1822]
We get a "Unauthorized: You are not allowed to access '...' in this context" (even with a manager account) when the default page of a folder is set to a private state. The problem can be reproduced in Plone 4.3.11 and Products.LinguaPlone 4.1.5.

The breaking change is here: https://github.com/plone/Products.LinguaPlone/commit/057cd6ac8c646f614dc25f5fa7acb3d98a339d7b#diff-cedfda5be1c808e676411ac261bb12efL17

We managed to fix it by changing Products/LinguaPlone/browser/defaultpage.py (Line 17):

``page = self.context.restrictedTraverse([default_page])``
to:
``page = self.context.unrestrictedTraverse([default_page])``

**Comment by cyriltata** [comment]
+1 to this. Experienced this error too

**Comment by mauritsvanrees** [comment]
If the default page is private and the folder is public, then I would say this is a configuration error. The best solution would be to either publish the default page, or make the folder private, so that the two workflow states match.

Without LinguaPlone, I would expect the same behavior as you describe. A private page should not be shown to anonymous users, even when it is the default page of a public folder.

So I am inclined to say: "This is not a bug, it is a feature."

I do think there is some code in Plone that tries to keep the two in sync: if both are public, and you make one of them private, then the other is made private too. And the other way around. But maybe I am imagining this. Or maybe that improvement is only in Plone 5. I do know I sometimes ran into this myself.

**Comment by mck9** [comment]
> A private page should not be shown to anonymous users, even when it is the default page of a public folder.
Sure. The problem is even the manager can't access the page and the folder anymore. That's not a feature.

**Comment by cyriltata** [comment]
@mauritsvanrees This also happens when both the folder and the page are both private

**Comment by mauritsvanrees** [comment]
Ah, sorry, I overlooked the part where you mentioned this also happens for a Manager.
I have created a pull request for this

**Comment by mauritsvanrees** [comment]
I have released Products.LinguaPlone 4.1.7 with this fix.
