### ISSUE TITLE
Plone 5.0.7 file icons not shown

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#1997]
With Plone 5.0.7, if you add a File you can see the file type icon correctly when editing the File but not when just viewing it.

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (pdf.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (plone-compiled.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (plone-logged-in-compiled.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (plone-compiled.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (plone-logged-in-compiled.min.js.map, line 0)
```

![screen shot 2017-04-08 at apr 8 5 40 08 pm](https://cloud.githubusercontent.com/assets/815418/24833006/0e73d7c8-1c83-11e7-94e2-7a4801b97d66.jpg)
![screen shot 2017-04-08 at apr 8 5 40 18 pm](https://cloud.githubusercontent.com/assets/815418/24833008/0e804bfc-1c83-11e7-97c4-081501162dcb.jpg)
![screen shot 2017-04-08 at apr 8 5 40 29 pm](https://cloud.githubusercontent.com/assets/815418/24833007/0e7f78bc-1c83-11e7-921c-e0eb10b4f8ff.jpg)
![screen shot 2017-04-08 at apr 8 5 41 09 pm](https://cloud.githubusercontent.com/assets/815418/24833009/0e824560-1c83-11e7-9e30-97ee6a3a8939.jpg)

**Comment by fgrcon** [comment]
icons were moved from  skins folder to a browser resourceDirectory nameed "mimetype.icons" in https://github.com/plone/Products.MimetypesRegistry/commit/61acf8327e5c844bff9e5c5676170aaf0ee2c323

versions.cfg:
Products.MimetypesRegistry should point to 2.1 !

**Comment by mauritsvanrees** [comment]
Plone coredev 5.0 is using `Products.MimetypesRegistry` branch 2.0.x, see [`sources.cfg`](https://github.com/plone/buildout.coredev/blob/5.0/sources.cfg#L178). So we shouldn't use version 2.1. It causes test failures on Jenkins:
- [5.0](http://jenkins.plone.org/job/plone-5.0-python-2.7/5570/)
- [5.0 AT} (http://jenkins.plone.org/job/plone-5.0-python-2.7-at/5687/)
The reason that we use 2.0x and not master, is precisely because the icons got moved: that move is better done in 5.1.
So this needs either a different fix, or some extra test fixes. For now, I have reverted your change.

**Comment by thet** [comment]
Fixed via: https://github.com/plone/plone.app.contenttypes/pull/395
