### ISSUE TITLE
Support Pinterest in social settings

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2004]
The social settings in Plone 5 handle Facebook and Twitter. It would be nice to add Pinterest there, giving a meta tag like this:

```
<meta name="p:domain_verify" content="abc123"/>
```

I can do the work. I did the same in Plone 4 for [`collective.ogtags`](https://github.com/collective/collective.ogtags/commit/505f6e85fefe6214d1fc5869780630f0e69b0fb8). Needed are basically the same changes as in that package:

- [ ] `Products.CMFPlone`: add `pinterest_id` in social controlpanel interface
- [ ] `plone.app.layout`: include Pinterest meta tag if the setting is filled in
- [ ] `plone.app.upgrade`: register the interface again in the configuration registry, so the new record is added.

It's a small change, so can be done in Plone 5.0 and 5.1 I think.

Is it okay if I add this?

**Comment by hvelarde** [comment]
an this is why adding social media support via an add-on was a saner idea from the very beginning; tomorrow, somebody will ask for LinkedIn, WhatsApp, Telegram and so on, and yet we'll finish with limited support of all of them.

**Comment by hvelarde** [comment]
let me explain a little bit more why I was against this because you may not know it: TL;DR it's proprietary.

when we were reviewing the PR that added social networks support to Plone I argued against the inclusion of Twitter Cards data for the same reason: Plone core should only support open standards and neither Twitter's, nor Pinterest are examples of such.

having this on an add-on, on the other side is better for many reasons including:

* is simpler to implement, as you only have to modify things in one package instead of 3
* you can support many Plone versions with the same code base making fixes and updates easier
* is faster to deliver, as you don't have to deal with people like me giving my opinion

unfortunately that discussion was lost when we killed the old Trac system; we need another discussion around this issue the sooner the better.

**Comment by gforcada** [comment]
If the amount of "proprietary" code we need to support is just a single meta tag I'm :+1: on it, for the ones that would involve more invasive changes I would rather keep them as an add-on.

@hvelarde your "simpler to implement" argument does not hold so much true given the amount of difficulties that supporting both Plone 4 and Plone 5 is for some add-ons...

I don't think it make sense to end up with +10 different social networks with all their custom tags and what not, but if *supporting* them only means this trivial work it's yet another reason for a Plone with batteries included, and let's face it, nowadays if you do not have proper metatags so that social networks do find the stuff they want, you will loose a lot of clicks and visits.

**Comment by hvelarde** [comment]
@gforcada I'm against to opening the door to proprietary stuff in the core, no matter how easy could be to support it; who will decide which feature enters the core or not? there are many other things to solve first to get more clicks and visits than adding this that, BTW, it's so easy that can be implemented in the site theme in less time that the one we have spent discussing this.

the simpler to implement argument is true: nobody is talking about supporting 2 different mayor Plone versions.

**Comment by gforcada** [comment]
Now that I think of it, it could make sense to have a generic ``<meta>`` tags editor on the control panel. This way, be it fo social networks, be it for you analytics, etc etc, if you ever have to stuff something on a meta tag, there would be a TTW editor for it!

**Comment by hvelarde** [comment]
but we already have a package to insert those kind of nasty things: https://github.com/simplesconsultoria/collective.blueline

**Comment by tkimnguyen** [comment]
sorry to sound like a broken record: Castle includes that, if it helps: https://github.com/castlecms/castle.cms/search?utf8=✓&q=pinterest&type=

**Comment by hvelarde** [comment]
awesome! good for you! I don't use CastleCMS and is not on my future plans neither; I use Plone and I want to keep it free from proprietary stuff.

sc.social like includes support for Pinterest also since many years ago and I have never use it neither.

**Comment by tkimnguyen** [comment]
It was more to show an example of how it could be done, but yeah if you want to "upgrade to Castle" you know whom to call ;)

**Comment by hvelarde** [comment]
you've learned too much marketing in your years in the US ;-)

**Comment by hvelarde** [comment]
I'm reviewing this as part of a new feature for sc.social.like; TL;DR Pinterest offers an additional method to confirm the ownership of a website: uploading an HTML file

https://help.pinterest.com/en/articles/confirm-your-website

@mauritsvanrees I think this is way too specific and must not be part of the core at all; you can even implement this with an alias in your frontend web server.
