### ISSUE TITLE
Disabling Icons and/or thumbs globally is broken 

### ISSUE THREAD

**Issue by fgrcon** [plone/Products.CMFPlone#2077]
In Site control panel:

![global-settings-thumbs-icons](https://user-images.githubusercontent.com/1640384/27228828-78d7f296-52a9-11e7-820a-e1326cd53aee.jpg).

If visibility globally  is set to  never or  no for anonymous users. css class `icons-off` or `thumbs-off` are generated in the body tag (plone.app.layout).  Dependant on this further  classes for thumbs are used to suppress those preview images. 
```
//supress thumbs when globally turned off
.thumbs-off  img[class*='image-scalename'] {
  display: none;
}
```

Unfortunately these classes are named **image-scalename instead of thumb-scalename**. the existing names are confusing and conflict with other class names ( e.g. image-left etc. used for tinymce ...)

**Comment by fgrcon** [comment]
@thet, @jensens, .... 

done !
PRS to merge: 

- [ ] - https://github.com/plone/plone.app.event/pull/259
- [ ] - https://github.com/plone/plone.portlet.collection/pull/18
- [ ] - https://github.com/plone/plone.app.portlets/pull/101
- [ ] - https://github.com/plone/plone.app.content/pull/132
- [ ] - https://github.com/plone/plone.app.layout/pull/125
- [ ] - https://github.com/plone/mockup/pull/779
- [ ] - https://github.com/plone/plone.app.contenttypes/pull/412
- [ ] - https://github.com/plone/Products.CMFPlone/pull/2078  (including recompilation of plone and plone-logged-in)

http://jenkins.plone.org/job/pull-request-5.1/184 
includes also  (trivial modifications)

- [ ] https://github.com/plone/plone.app.portlets/pull/100 
- [ ] https://github.com/plone/plone.app.contenttypes/pull/411

**Comment by thet** [comment]
If this is merged it's better done soon because this PR touches again many repositories.

Although I hesitate to merge it.

Those ``image-`` classes are in place since more than a year now and the selectors might already be used. 
AFAIK, by the ``image-`` classes were added via these and other commits - https://github.com/plone/plone.app.contenttypes/commit/3cfc044ad8061907967fe84b2c638461e93e7ce5

I agree that ``thumb-`` would be more appropriate but having more generic class names has also a benefit - one must just define one CSS class name and use it for any image type.

I know, that's now coming from me who was so picky about the distinction between "thumb scale" and "thumb size"....

I need some more opinions here - @jensens @gforcada

**Comment by thet** [comment]
@fgrcon ah, this is actually about fixing a bug.

Please point me to where the ``.thumb-off`` CSS is statement.

Regarding the css statement above I think it should read:
```
//supress thumbs when globally turned off
.thumbs-off  img[class^='thumb-'] {
  display: none;
}
```

instead of ``image-scalename`` just ``thumb-`` (provided the renaming is merged) plus using ``^=`` should be more performant than ``*=`` as it only searches the beginning of an string.

**Comment by thet** [comment]
I think I understand the issue better via this comment: https://github.com/plone/mockup/pull/774#issuecomment-309026225

Well, I think the PR is fine and I approve it.

**Comment by thet** [comment]
All merged. Closing this issue.
