### ISSUE TITLE
Plone 5.1: inconsistent add-on control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2166]
I have this buildout 

https://github.com/zopyx/pappnasen-plone5/

to plone-demo.info.

I am trying to port it from Plone 5.0 to 5.1.

It uses the following two script to setup the Plone demo instance:

https://github.com/zopyx/pappnasen-plone5/blob/master/setup-plone.py

https://github.com/zopyx/pappnasen-plone5/blob/master/setup-smashdocs.py

The `zopyx.smashdocs` add-on is installed by one of the setup scripts. 

The control panel lists the add-on as installable however it is already installed as the existing Smashdocs control panel indicated.

Tested against Plone 5.1 RC1

<img width="886" alt="bildschirmfoto 2017-10-05 um 20 21 11" src="https://user-images.githubusercontent.com/594239/31245630-3c5a1a56-aa0b-11e7-9e63-e69dc82856b5.png">

<img width="296" alt="bildschirmfoto 2017-10-05 um 20 21 17" src="https://user-images.githubusercontent.com/594239/31245638-400eb058-aa0b-11e7-9341-ef5ecac23d48.png">

**Comment by hvelarde** [comment]
maybe @mauritsvanrees can give some hints over this.

**Comment by hvelarde** [comment]
you may find some pointer is #1340 also; I think this is clear also for me now.

IIRC @mauritsvanrees documented that also; feel free to open a new issue in the documentation repo in case is not there.

**Comment by zopyx** [comment]
Why did you close this obvious bug without further explanation? I did not find anything in #1340. The described behavior is odd and wrong. An obviously installed add-on should not be listed  as installable but as installed. If there is some issue with the profile configuration then it should be reported or logged somehow as an error but should not leave the control panel in a weird state.

**Comment by mauritsvanrees** [comment]
This is similar to #2103, but that one already goes wrong when going from 4.3 to 5.0 and is specific for add-ons in the Products namespace.

I'll see next week if I can find out what is wrong here.

**Comment by hvelarde** [comment]
@zopyx sorry about that: I obviously pressed the wrong button.

**Comment by mauritsvanrees** [comment]
I can confirm it with your example buildout.

Your product has three profiles: `default`, `uninstall` and `SMASHDOCs integration with Plone (SD only)`. (I would suggest a shorter name for that last one, but okay.)
It goes wrong because the last profile name starts with an uppercase character, which makes it sort alphabetically before `default`. That used to be a bad idea for exactly the reason you are seeing.

In Plone 5.1 it *should* be fine: `default` should be recognised as the profile to use for installing. But something is off in the logic. I will fix that.

Workaround: rename the last profile to `smashdocs` or something else that sorts alphabetically after `default`.

**Comment by zopyx** [comment]
Renaming the profile as suggest solves this issue for me. The bad name is clearly a copy&paste error.
