### ISSUE TITLE
folder_contents 5.1RC2 untranslated properties dialog

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2313]
See screenshot (DE)

![props](https://user-images.githubusercontent.com/594239/36417333-f2293f42-162b-11e8-8997-b5feca2c2679.png)

**Comment by malikrohit16** [comment]
Hello @zopyx I want to work on it. Can you tell me where to find the respective file for the changes?

**Comment by cewing** [comment]
@malikrohit16 since this issue has to do with missing translations in content, a good first step would be to learn about [how to edit translations in Plone](https://docs.plone.org/develop/plone/i18n/contribute_to_translations.html#how-to-contribute-to-plone-core-translations).  Once you've got that working, you can find the code responsible for building this view (which is showing the "settings" tab for a piece of content.  This should keep you busy for a bit, while @zopyx and @jensens work up a more complete reply.

**Comment by vincentfretin** [comment]
As far as can see, the fields name and descriptions of the add/edit form of the different content types in German are properly translated now.
There is some issues left in richtext tracked here #3120
If there are other places, please create a separate ticket.

**Comment by vincentfretin** [comment]
Ah sorry this was not the edit/add form, it was in folder contents, I found the dialog you talked about.
There is some things that was fixed, but there is still some issues:
- Modify properties on items
- No change

![folder_contents](https://user-images.githubusercontent.com/112249/85116764-1cca3b80-b21e-11ea-8512-796afe678e94.png)

![Capture d’écran de 2020-06-19 11-15-42](https://user-images.githubusercontent.com/112249/85116887-46836280-b21e-11ea-9f36-08562ae833e5.png)

**Comment by vincentfretin** [comment]
some other i18n issues in #2188

**Comment by erral** [comment]
Closed by https://github.com/plone/plone.app.content/pull/205
