### ISSUE TITLE
Can not build "plone-logged-in" through the web

### ISSUE THREAD

**Issue by krissik** [plone/Products.CMFPlone#2396]
### What I did:

I want to build "plone-logged-in" bundle ttw so I clicked "Build" in "Resource Registries"

### What I expect to happen:

That it builds without any error.

### What actually happened:

I see a lot of compilation errors.

```
less compilation error on file http://demo.plone.de/++plone++static/plone-logged-in.less: Error: 'http://demo.plone.de/++plone++static/components//tinymce-builded/js/tinymce/skins/lightgray/skin.less' wasn't found (404)
```

![demo-plone-org-compile-plone-logged-in-error](https://user-images.githubusercontent.com/5301889/39521542-36833542-4e0f-11e8-886f-da05c0e78291.png)

I can reproduce it on demo.plone.org.

### What version of Plone/ Addons I am using:

Plone 5.1.1

### What I found out

There are no less files in `Products/CMFPlone/static/components/tinymce-builded/js/tinymce/skins/lightgray` in release package.

**Comment by gp54321** [comment]
IIRC I pointed this problem in the 5.1.1 soft-release process:
https://community.plone.org/t/plone-5-1-1-soft-released/6159/2
it was fixed later and should not appear anymore in 5.1.2 (unfortunately this release is still pending and has its own problems).

**Comment by gp54321** [comment]
I can't help you with TTW rebuilding of system bundles because I have given up on it; however I can point that plone-compile-resources works all right for Plone 5.1.2 for system bundles rebuilding, and, even if it's not as 'user friendly' as TTW should really be preferred for this task, if only because if something goes wrong while rebuilding TTW, it can remove the very possibility to do another rebuild TTW - with TTW system resources rebuilding it takes a running Plone to rebuild resources, but rebuilding resources can break the control panel. Moreover the very idea of rebuilding server resources in an environment as instable as a browser is just strange. That's my 2 cents (I am NOT a Plone developer BTW)

**Comment by jensens** [comment]
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.
