### ISSUE TITLE
Port plone.rest and plone.restapi to Python 3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2474]
In https://github.com/plone/plone.rest/pull/75 and https://github.com/plone/plone.restapi/pull/542 I started to work in this. 

First the dependency on Archetypes should be removed (that could probably be done much cleaner  that how I did it) and then the failures on py3 should be fixed.

**Comment by lukasgraf** [comment]
No worries. Who would have thought that a message service limited to 140 characters could ever lead to misunderstandings 😉 And while I can't fully commit myself to this, I'll of course still try to help where and when I can.

**Comment by frapell** [comment]
@pbauer @lukasgraf I would like to work in this... Running the tests for plone.rest with py3.cfg has only 1 failure:

```
AssertionError: 'ERROR: Another exception happened before we could render the traceback.' is not an instance of <class 'list'>
```

Happening at "test_error_handling.py", line 118, in test_500_traceback_only_for_manager_users

Any pointers as to what would be the appropriate way to fix it?

**Comment by davisagli** [comment]
@frapell https://github.com/plone/plone.rest/pull/75#issuecomment-404971502 has a comment at the bottom about that one.

**Comment by frapell** [comment]
@davisagli Thanks! I had missed that one... Now, I guess the Publisher is ok, and I should change plone.rest behavior to be aware of this, what do you think?

**Comment by davisagli** [comment]
@frapell the publisher still normalizes exceptions, for example turning zope.publisher's NotFound into zExceptions NotFound -- that happens here: https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/WSGIPublisher.py#L137 ... Maybe that line in plone.rest can compare the class names of the two exceptions instead of using `is`

**Comment by frapell** [comment]
@davisagli Yeah, saw that line from the comment you referenced... My guess was that the Publisher is correct and plone.rest is the one that should be fixed... I am not experienced with plone.rest nor with WSGIPublisher, that's why I was asking your thoughts :)

Alright, will try exploring that route and see if it works. Thanks !
