### ISSUE TITLE
Datatables CSS not available

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#2512]
The current ``plone-logged-in-compiled.min.css`` bundle file does not directly include the datatables css files but tries to import them. Also the paths are wrong which leads to a bunch of 404's - at least for me. See the first line here:

https://github.com/plone/Products.CMFPlone/blob/7cefb8f47585422c182e04ae15b08dd2ea456616/Products/CMFPlone/static/plone-logged-in-compiled.css

The CSS files mist be included inline.
This  - among other things - fixes this problem: 

https://github.com/plone/mockup/pull/863

/cc @plone/framework-team @plone/release-team

**Comment by datakurre** [comment]
I’m sorry about that. I didn’t realise that difference between inline and css imports.

The difference with webpack was that css import let webpack’s css loader to do the inlining fixing some lookup issues with less loader (it was unable to find relative paths linked from unlined css because of lost original folder context).

So, probably you should revert and use inline, and I should figure out if less loader could patch those inline imports to css imports.
