### ISSUE TITLE
Navigating within the folder contents does not update the URL of the "View" action in the toolbar.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2531]
When you navigation using the folder contents view through a hierarchy of documents then URL of the toolbar's view action does not relate to the URL of the current folder of the folder contents view. 
This is a usability. As a content author I want to see the view of the current folder and not view of the folder that was used to start the initial folder contents view from....usuality fail.

**Comment by sunew** [comment]
This is a clear bug, not just usability. It is related to https://github.com/plone/Products.CMFPlone/issues/2395
(at least same kind of issue)
and https://github.com/plone/mockup/pull/858

**Comment by tisto** [comment]
@zopyx I think the UX part of this bug is already reported here: https://github.com/plone/Products.CMFPlone/issues/1475

**Comment by thet** [comment]
Should already be fixed in:
https://github.com/plone/Products.CMFPlone/pull/2398
https://github.com/plone/Products.CMFPlone/pull/2399

But for sure in 5.1.5 with:
https://github.com/plone/Products.CMFPlone/pull/2563
https://github.com/plone/plonetheme.barceloneta/pull/165

If it's not, it might be a resource caching problem, where @sunew knows more about it and we're investigating it tomorrow.

**Comment by ucalligaro** [comment]
It seems that this problem reoccur in version 5.2.2.
