### ISSUE TITLE
Effective/Expires: if time is not set nothing is saved, fails silently (DX IPublication).

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#271]
If one selects a date but no time the value is not saved and no error message appears.
This is valid for Plone 4.3 with plone.app.contenttypes. We cant test if this is valid for 5.0 because of #270.

In my opinion a missing time should either default to 0:00 or result in a validation error.

**Comment by do3cc** [comment]
It seems the pattern is at fault here. When selecting only a date, only an empty string is being submitted to the backend

**Comment by do3cc** [comment]
Here is the if statement in the pattern that unconditionally does not update the value, if the other (time) field is not filled out:
https://github.com/plone/mockup/blob/master/mockup/patterns/pickadate/pattern.js#L160

I am not sure, but maybe setting a css class when only one of two fields has data, might make more sense than setting a default value. Because one can also only set a time, in such a case it is not so clear, what should be the default date.

**Comment by jensens** [comment]
this works meanwhile

**Comment by tomgross** [comment]
Not for me

**Comment by cekk** [comment]
Yes, if this issue is related to the other opened on mockup, it doesn't work neither for me

**Comment by tomgross** [comment]
Has anyone a solution for this?

**Comment by jensens** [comment]
Afaik @thetet fixed this for 5.1. Johannes, may you follow up here?

**Comment by jensens** [comment]
cc @thet

**Comment by thet** [comment]
Fixed here Plone 5.1: https://github.com/plone/mockup/pull/726 and Plone 5.0: https://github.com/plone/mockup/pull/727
