### ISSUE TITLE
Delete icon in select2 in misalligned

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2785]
In Plone 5.2rc1 and current coredev the improvements of the related items widget spilled over to the Tags widget and the tags are no longer readable and the 'x' is not clearly visible. 

<img width="580" alt="bildschirmfoto 2019-03-05 um 16 01 46" src="https://user-images.githubusercontent.com/453208/53814610-316abd80-3f60-11e9-8b76-9e9447aebdad.png">

See http://demo-latest-py3.plone.org/en/demo/a-page/edit for a live-demo.

**Comment by MrTango** [comment]
I guess we need to make the css selector more specific there, so that it only has an effect on relateditems, but not on all select2 widgets. @davilima6 if you can have a look, that would be awesome, since I'm still fighting with the tox setup in bobtemplates.plone and also have some other urgent things this week ;)

**Comment by davilima6** [comment]
@MrTango, it was already merged but could you please double check all is good while using the widget?
