### ISSUE TITLE
Jenkins robot setup sometimes fails

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#2786]
The Jenkins 5.2 robot tests regularly have a failure on Python 3.
Most tests will pass, but one or two fail with something like this:

```
Setup failed:
ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Also teardown failed:
No browser is open.
```

See for example https://jenkins.plone.org/job/plone-5.2-python-3.7-robot-chrome/559/robot/ and https://jenkins.plone.org/job/plone-5.2-python-3.6-robot-chrome/584/robot/

When searching for 'robotframework ConnectionResetError' I stumbled upon a [fix in CumulusCI](https://github.com/SFDO-Tooling/CumulusCI/pull/922/files) by none other than @davisagli.

David, does this sound like the same error? Any idea where and how to fix this in Plone? Can we add a similar retry somewhere in `plone.app.robotframework`?

**Comment by davisagli** [comment]
Ha, that's a funny coincidence! Yes, it sounds like it is probably the same error. I tracked the problem down to a bug in selenium due to a difference in how socket exceptions are structured in Python 3. In Python 2 this line used to catch connection resets but in Python 3 it does not: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/common/utils.py#L108

**Comment by mauritsvanrees** [comment]
Thanks.
So that seems to be https://github.com/SeleniumHQ/selenium/issues/6438 and possibly that would be fixed with https://github.com/SeleniumHQ/selenium/pull/6480.

**Comment by mauritsvanrees** [comment]
I have created a PR to patch the Selenium `is_connectable` function in Python 3.
See https://github.com/plone/plone.app.robotframework/pull/108
