### ISSUE TITLE
When NOT Installing Barceloneta, plone.scripts Break

### ISSUE THREAD

**Issue by Netroxen** [plone/Products.CMFPlone#2870]
### What I did:

* Install a Plone 5.2rc2/Plone 5.2rc3 instance using the advanced ZMI setup screen.
* Unselect and DO NOT install the Barceloneta Theme Add-On.
* Go to the Plone site and log out (there is no styling, this is to be expected...)
* Go to a non-existing view or URL path i.e. localhost:8080/Plone/xxxxxxxxxx
* Page will be blank...
* Now inspect the DOM head element, all scripts and links as well as some HTML elements are placed into a JavaScript script tag.

![Peek 2019-05-21 18-03](https://user-images.githubusercontent.com/7691449/58112303-8929d400-7bf3-11e9-98fa-d8a807c0bc48.gif)

### What I expect to happen:

* Script and link elements are placed into the head element correctly...

### What actually happened:

* All script and link elements are inlined (as HTML) in a JavaScript script tag...

### What version of Plone / Addons I am using:

Plone 5.2rc2/rc3 (not tested on earlier versions)

### Additional information:

* Removing the plone.scripts provider in the main_template.pt partially solves the issue, although no JavaScript is now rendered.
* This is causing an issue for the https://github.com/collective/plonetheme.tokyo (which re-themes Plone without Barceloneta) as no styling is available when logged out

**Comment by sarn0ld** [comment]
The problem seems to be the closing of the <script>-tag in Products.CMFPlone.resources.browser.scripts.pt
Replacing `<script/>` with `<script></script>` is fixing the issue.

A workaround is to override the file Products.CMFPlone.resources.browser.scripts.pt with jbot.
I'll attach a file with working code:
[Products.CMFPlone.resources.browser.scripts.txt](https://github.com/plone/Products.CMFPlone/files/3206861/Products.CMFPlone.resources.browser.scripts.txt)

**Comment by tmassman** [comment]
Fix available since 5.2rc4.
