### ISSUE TITLE
Enable CHAMELEON_CACHE by default

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#2898]
Setting the `CHAMELEON_CACHE` (https://chameleon.readthedocs.io/en/latest/configuration.html) yields a speed-increase of more than 20% when running test of coredev. The speed-increase when running in production could be similar.

See https://github.com/plone/Products.CMFPlone/issues/2890#issuecomment-504657392 for the original finding.

I propose to configure a `CHAMELEON_CACHE` location by default in `plone.recipe.zope2instance`. The default-location could be `${buildout:directory}/var/cache`. The recipe has to make sure the directory exists.

**Comment by davisagli** [comment]
+1, I was using this in production for some projects for years.

**Comment by jensens** [comment]
FTR: It just speeds up tests and restart, a running Plone instance is at the same speed.
I suppose in debug mode the template reload still works with this settings?

**Comment by mauritsvanrees** [comment]
The change is good, but did this **actually** make the tests in coredev faster? I think not, because `bin/test` is not using the chameleon cache. We should add `CHAMELEON_CACHE` to the [test environment](https://github.com/plone/buildout.coredev/blob/5.2/tests.cfg#L211-L215).

On my laptop, the CMFPlone tests (without robot tests) in 5.2 took:
- 6 minutes 48 without CHAMELEON_CACHE,
- 5 minutes 17 with CHAMELEON_CACHE, first run, or a 22 % speedup,
- 4 minutes 53 with CHAMELEON_CACHE, second run, or an extra 8 percent speedup, or 29 percent in total.

Let me make a PR.
