### ISSUE TITLE
Mixed Content on first run

### ISSUE THREAD

**Issue by avoinea** [plone/Products.CMFPlone#2981]
### What I did:

Serve Plone at https://new.mydomain.id/

### What I expect to happen:

No JS errors within browser debug console

### What actually happened:

```
Mixed Content: The page at 'https://new.mydomain.id/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,300,700'. This request has been blocked; the content must be served over HTTP

Mixed Content: The page at 'https://new.mydomain.id/' was loaded over HTTPS, but requested an insecure stylesheet 'http://new.mydomain.id/++resource++plone-admin-ui.css'. This request has been blocked; the content must be served over HTTPS.
```
### What version of Plone/ Addons I am using:

Plone 5.2.0

See more: https://github.com/plone/plone.docker/issues/126

**Comment by auspex** [comment]
In what way was this "completed"? The OP at plone/plone.docker#126 asked if there were environment variables to be passed, @avoinea opened this issue as a bug, and it's closed (four years later) but there's still no suggestion how to get around the problem. I vaguely remember how to configure the VHM **IF** I can get into Plone, but atm I can't do that because of this issue.

ETA: OK, I've found @jensens https://github.com/jensens/ansible-docker-swarm-plone-cluster/blob/main/plone/docker-compose.yml which neatly handles the problem. I'm not at all sure that's _why_ this issue was closed but some mention of the solution would have been nice.
