### ISSUE TITLE
Only build travis for PR

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#3087]
If travis is used in repositories on the plone and collective organisations there is currently a build started for each branch and each pull request.

Also, there is a new Travis setting to automatically cancel builds for branches and pull requests if new commits were made.

For our development workflow it should be enough to only build for pull requests and cancel all running builds once there is a new commit on the pull request. This will help not exceeding any rate limits and reduce Plone's environmental footprint.

Current situation on a PR - branch and PR builds were made:
![Screenshot from 2020-04-21 11-18-44](https://user-images.githubusercontent.com/170891/79848883-faed3d80-83c1-11ea-9c38-bcd0219ea1bf.png)

Old and default setting repositories, e.g.: https://travis-ci.com/github/collective/collective.auditlog/settings (you have to log in and have access rights)
![Screenshot from 2020-04-21 11-09-58](https://user-images.githubusercontent.com/170891/79848963-1d7f5680-83c2-11ea-922d-e6b249025593.png)

Should change into (already done for collective.auditlog):
![Screenshot from 2020-04-21 11-21-40](https://user-images.githubusercontent.com/170891/79849112-56b7c680-83c2-11ea-831d-e263ee6c63aa.png)

Docs: https://docs.travis-ci.com/user/customizing-the-build/

I did not found an option to set this for all repositories in an organization. I hope there is an API for that, but I'm not sure: https://docs.travis-ci.com/user/developer/

@gforcada @mauritsvanrees

**Comment by mauritsvanrees** [comment]
Sounds good to me.

I often also see a PR job and a push job. The push job tries to merge the PR and then runs the tests. In my experience the push job is almost always useless, because often the PR branch has been created from master and no other commits have been done there. There can be exceptions, but for me it would be fine to disable.

In your last screen shot, I see it says "Builds will only be cancelled if they are waiting to run". So a jobs that has already started, will continue. Still, seems good.

But yes, setting this for all repositories at once would be best, although some collective owners may not agree. If we do it once, and announce it, people could undo the change for repositories that they care about.

But I am not going to click through hundreds of pages on Travis, so this would indeed need some automation.
We can also tweak settings as we go along: when you make a PR and see that too many jobs are run, login and fix it.

**Comment by thet** [comment]
@pbauer maybe it makes sense to include this info in the training docs.

**Comment by icemac** [comment]
I might not agree with the actual settings but would be interested in the automation tool to use it on the zopefoundation repositories. Is there already such a tool or has it still to be written? Maybe at Zope May sprint could be some time to write such a tool if it does not yet exist.

**Comment by thet** [comment]
I don't know of any such tool yet. I quickly scanned the API docs and unfortunately it doesn't seem that there are any endpoints for the settings mentioned above.

**Comment by thet** [comment]
Closing this. We're not using Travis anymore.
