### ISSUE TITLE
The attrs variable is not available anymore in page template

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3135]
### What I did:

Upgraded my code to Plone 5.2.2

### What I expect to happen:

It is a minor change, everything should be fine!

### What actually happened:

I have a page template like this:
```
<div foo="bar"
     tal:attributes="foo string:${attrs/foo} baz"
></div>
```
that fails to render:
```
  File "/home/ale/.buildout/eggs/Chameleon-3.8.0-py3.8.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "5823e51a055e4b8c62b075c531a9daf8.py", line 1617, in render
  File "/home/ale/.buildout/eggs/zope.tales-5.0.2-py3.8.egg/zope/tales/pythonexpr.py", line 73, in __call__
    return eval(self._code, vars)
   - __traceback_info__: (chv.safe_member_and_group_prefill(context, attrs['name']))
  File "<string>", line 1, in <module>
NameError: name 'attrs' is not defined
```

Instead according to https://zope.readthedocs.io/en/latest/zopebook/AppendixC.html#built-in-names it should be there.

### What version of Plone/ Addons I am using:

- Plone 5.2.2-pending (buildout.coredev)

**Comment by vincentfretin** [comment]
So what version of Chameleon should we use then in Plone 5.2.2?

**Comment by ale-rt** [comment]
Good question! My idea is that we should stick with the latest Chameleon.
I do not think this is a Chameleon issue the tests cover the `attrs` builtin (https://github.com/malthe/chameleon/blob/7f901e9714705b468b2b36b2eef1acaa238d16d5/src/chameleon/tests/inputs/008-builtins.pt).
Also I tried to reproduce the error in plain Zope and was not able to.
I need to investigate this further.

**Comment by mauritsvanrees** [comment]
This report seems similar: https://community.plone.org/t/plone-5-2-2-soft-released/12487/17?u=mauritsvanrees
`<p tal:condition="True" >` throws KeyError: 'True'. I would expect condition `python:True` here, but apparently it worked before.
Worth creating an issue in Zope or Chameleon, if not done already. There have been various changes in Zope templates/tales/chameleon, which took several releases to get right. Subtle bugs.

**Comment by mauritsvanrees** [comment]
Maybe somewhat related: https://github.com/malthe/chameleon/issues/316

**Comment by mauritsvanrees** [comment]
For recently fixed problems with Zope, Chameleon and the default keyword, see https://github.com/zopefoundation/Zope/pull/853
And for changes in the handling of TALES, see https://github.com/zopefoundation/Zope/pull/807

**Comment by vincentfretin** [comment]
For `<p tal:condition="True" >` that throws KeyError: 'True'.
@d-maurer said in https://github.com/zopefoundation/Zope/pull/807#issuecomment-602066142
that `True` and `False` are not available in path expressions.
But I don't understand why it is not available anymore.

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-1 00:32 -0700:
>For `<p tal:condition="True" >` that throws KeyError: 'True'.
>@d-maurer said in https://github.com/zopefoundation/Zope/pull/807#issuecomment-602066142
>that `True` and `False` are not available in path expressions.
>But I don't understand why it is not available anymore.

`True` and `False` are available in Python expressions.

When you do not specify an expression type, "path" is assumed.
For a "path" expression, the first component must be
one of the defined "variable"s. Some "variable"s are
initially defined (e.g. "context", "request", "nothing", "default", ...);
others you can define (e.g. with "tal:define").

The spec indicates that `nothing` has a Python false
and `default` a python true value. You can those two
use in path expressions as an emulation of `False` and `True`,
respectively.

**Comment by vincentfretin** [comment]
Thanks @d-maurer for the feedback. So it appears that `<p tal:condition="True" >` wasn't meant to work per the spec but it apparently did before (see https://community.plone.org/t/plone-5-2-2-soft-released/12487/17). For this one, I'd say fix your code to use `python:True` :-)

What about the `attrs` described by @ale-rt in the description of this issue?

**Comment by vincentfretin** [comment]
For completeness about the True/False in path expression, stevepiercy said in https://community.plone.org/t/plone-5-2-2-soft-released/12487/18 they had to do changes in deform and pyramid_chameleon because it didn't work anymore in chameleon 3.8.0.

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-1 06:19 -0700:
>Thanks @d-maurer for the feedback. So it appears that `<p tal:condition="True" >` wasn't meant to work per the spec but it apparently did before (see https://community.plone.org/t/plone-5-2-2-soft-released/12487/17). For this one, I'd say fix your code to use `python:True` :-)

The `chameleon` template engine comes with its own TALES implementation
and this was used by `Zope` for templates. This TALES
implementation has been responsible for the recognition of `True`
and `False` even in "path" expressions.

I changed the `chameleon` integration into Zope. Now, the template
decides whether it will use `zope.tales` (the TALES implementation
used elsewhere in the `Zope` world, e.g. `CMFCore`, `DVWorkflow`, some
portlets) or `chameleon.tales` -- with `zope.tales` has default.
`zope.tales` is more strict with respect to the specification -
especially, it does not define `True` and `False` for "path" expressions.


>What about the `attrs` described by @ale-rt in the description of this issue?

I do not know this feature -- I assume it was something
introduced by `chameleon` and supported (only) by `chameleon.tales`.
With `zope.tales`, there is a set of predefined "variable"s
(the various use cases define different predefined variable sets);
the template can add additional variables (e.g. via `tal:define`).
`addrs` is not such a predefined variable.

The `zope.tales` integration (into the `chameleon` template engine)
respects the `chameleon` `Scope` (it represents the currently defined
variables). Thus, if `chameleon` had used its `Scope` for the `attrs`
variable, it would work even with `zope.tales`. Apparently, `attrs`
was not truely treated as a variable but as something special.

**Comment by vincentfretin** [comment]
@ale-rt pointed to the documentation https://zope.readthedocs.io/en/latest/zopebook/AppendixC.html#built-in-names where it defines `attrs- - a dictionary containing the initial values of the attributes of the current statement tag.`
I don't know to what implementation this documentation is referring to, if it was for zope.tales or a chameleon specific feature.

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-1 07:58 -0700:
>@ale-rt pointed to the documentation https://zope.readthedocs.io/en/latest/zopebook/AppendixC.html#built-in-names where it defines `attrs- - a dictionary containing the initial values of the attributes of the current statement tag.`
>I don't know to what implementation this documentation is referring to, if it was for zope.tales or a chameleon specific feature.

Several of those variables have been lost with the switch to
`zope.tales`: `attrs`, `root`, `container`, `CONTEXTS`.

`attrs` requires support from the template engine (as only that
knows about the current element and its attributes). The other
variables can easily be supported.

Note that if `CONTEXTS` is really a list then it does not support
the stated purpose (access to hidden standard variables)

**Comment by vincentfretin** [comment]
Thanks for investigating and creating issues.

If we don't want to delay the Plone 5.2.2 release and to not include breaking changes in a minor version of Plone, does it make sense to downgrade chameleon to a version before the zope.tales switch that is included in Zope 4.4.4? To which version exactly? I can't say by just looking at the changelog. I guess maybe some tests will break because some have been adapted to the latest chamelon 3.8.0?

If it's not possible, I guess we release Plone 5.2.2 with chameleon 3.8.0 that can break some third party code...

**Comment by ale-rt** [comment]
Thank you all for checking this. 

@d-maurer do you know if there is a way to force chameleon.tales over zope.tales or viceversa?

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-1 23:13 -0700:
>If we don't want to delay the Plone 5.2.2 release and to not include breaking changes in a minor version of Plone, does it make sense to downgrade chameleon to a version before the zope.tales switch that is included in Zope 4.4.4? To which version exactly?

The major change comes from `Zope` - more precisely its
changed integration of the `chameleon` template engine.
This change happened in Zope 4.4:

- Fix issue 717 by fully honoring the engine returned by
  ``PageTemplate.pt_getEngine``
  (`#717 <https://github.com/zopefoundation/Zope/issues/717>`_).
  The engine also decides about the use of ``zope.tales``
  (engine is an instance of ``zope.pagetemplate.engine.ZopeBaseEngine``)
  or ``chameleon.tales`` (otherwise) TALES expressions.

If you downgrade to Zope 4.3, use "its" (i.e. the one
mentioned in its `contraints.txt`) `chameleon` version.

**Comment by d-maurer** [comment]
Alessandro Pisa wrote at 2020-7-1 23:16 -0700:
>@d-maurer do you know if there is a way to force chameleon.tales over zope.tales or viceversa?

`PageTemplates` have a method `_pt_getEngine`.
This method returns a TALES engine.

Before Zope 4.4, the engine returned by this method was mostly
ignored by the `chameleon` integration: that just superficially
looked at it to guess whether the engine should be trusted or untrusted
and then used its own (`chameleon.tales`) trusted/untrusted engine
ignoring any further details of the original TALES engine.
Since Zope 4.4, the TALES engine returned by `_pt_getEngine`
is used - even by the `chameleon` integration.
This implies that `_pt_getEngine` decides whether the
template wants a `zope.tales` or `chameleon.tales` TALES implementation.

**Comment by vincentfretin** [comment]
@d-maurer Thank you for your work on https://github.com/zopefoundation/Zope/issues/860
The Plone 5.2.2 release is currently postponed for at least a week. We will probably go back to Zope 4.3 for this release, see https://github.com/plone/buildout.coredev/pull/662

FYI we saw other templates breaking like `tal:omit-tag="True"` that worked previously. Is it possible to add back support for True and False in path expression?

Another issue reported is traversing macros https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-653098558

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-3 01:43 -0700:
> ...
>FYI we saw other templates breaking like `tal:omit-tag="True"` that worked previously. Is it possible to add back support for True and False in path expression?

In principle yes -- but those were never legal path
expressions according to the documentation.

I will prepare a PR and we will see what the other Zope
developers think about it.

>Another issue reported is traversing macros https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-653098558

I will look into this.

**Comment by d-maurer** [comment]
Vincent Fretin wrote at 2020-7-3 01:43 -0700:
> ...
>FYI we saw other templates breaking like `tal:omit-tag="True"` that worked previously. Is it possible to add back support for True and False in path expression?

I have created "https://github.com/zopefoundation/Zope/issues/863"
to discuss this question.

According to the documentation, "True" is not a legal
path expression. `zope.tales` adheres quite well to the
documentation - and therefore correctly rejects expressions
like the above -- in contrast to the formerly used path implementation
based on `z3c.pagetemplate`.

Of course, this could be changed in principle.


>Another issue reported is traversing macros https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-653098558

This issue is almost surely understood.

With high probability, the affected template does not derive
from `Products.PageTemplates` (but likely from `zope.pagetemplate`).
As a consequence, its `pt_getEngine` does not return
a `Zope` aware TALES engine.
Before `Zope 4.4` the return value of `pt_getEngine` was
mostly ignored - it was just used to guess (very roughly) whether
a trusted or untrusted engine should be used - the `chameleon`
integration then used a fixed (and `Zope` aware) trusted or untrusted
engine of its own. Since `Zope 4.4`, the returned engine is fully
honored.

It is not yet clear wether the issue above is
a custom/application problem (wrong template base class)
or a Plone integration problem (direct use of third party
templates rather than a `Zope` adaptation thereof).

I have created "https://github.com/zopefoundation/Zope/issues/864"
to discuss whether `Zope` should reinstate some sort
of TALES engine guessing, i.e. not honor the engine returned
by a template's `pt_getEngine` in some cases.

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2020-7-4 14:13 +0200:
>Vincent Fretin wrote at 2020-7-3 01:43 -0700:
>> ...
>>Another issue reported is traversing macros https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-653098558
>
>This issue is almost surely understood.
>
>With high probability, the affected template does not derive
>from `Products.PageTemplates` (but likely from `zope.pagetemplate`).
>As a consequence, its `pt_getEngine` does not return
>a `Zope` aware TALES engine.
> ...
>It is not yet clear wether the issue above is
>a custom/application problem (wrong template base class)
>or a Plone integration problem (direct use of third party
>templates rather than a `Zope` adaptation thereof).

Mauro confirmed in
"https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-653783918"
that the affected template is related to `z3c.form`.


When I remember right then `Plone` uses monkey patching at some
places to work around integration problems. The following
monkey patch might avoid the use of a `Zope` unaware TALES engine:

       from Products.PageTemplates.Expressions import getTrustedEngine
       from zope.pagetemplate import pagetemplate
       pagetemplate.Engine = getTrustedEngine()

It replaces the (trusted but `Zope` unaware) TALES engine
used by `zope.pagetemplate` as default by the standard
`Zope` trusted engine.
