### ISSUE TITLE
Content Type Icons no longer displayed in 5.2.2rc3

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3163]
https://github.com/plone/mockup/pull/1003/files#diff-a6b31c800683d65906ffb168530bb2aaL364 introduced a regression.
In the add-menu content-type icons are no longer displayed:

Before:
![before](https://user-images.githubusercontent.com/453208/89531644-da21ea00-d7f0-11ea-9dfc-ee1b145c8b19.png)

After:
![after](https://user-images.githubusercontent.com/453208/89531648-db531700-d7f0-11ea-8ef5-6a11ee1ccae8.png)

**Comment by vincentfretin** [comment]
I'll look into it today.

**Comment by vincentfretin** [comment]
Note, before my change, we had the issue only on Safari, because `&:not(.plone-toolbar-submenu-header, .plonetoolbar-display-view.actionSeparator)` rule was evaluated, and not in other browsers.

**Comment by vincentfretin** [comment]
`&:not(.plone-toolbar-submenu-header, .plonetoolbar-contenttype)` would fix it but it's only supported on Safari, not on Chrome and Firefox. I thought about adding additional rules to override what is in `&:not(.plone-toolbar-submenu-header)` but the icon defined with `:before {content: ...}` in `plonetheme/barceloneta/theme/less/contents.plone.less` is already lost with the `not:` rule redefined the content.
The only way I think of is instead of the rule
```
&:not(.plone-toolbar-submenu-header
```

add explicitly all submenus where we want the bullet point.
```
        &.plonetoolbar-workfow-transition,                                         
        &.plonetoolbar-content-action,                                          
        &.plonetoolbar-display-view,                                            
        &.plonetoolbar-portlet-manager,                                         
        &.user-action 
```

This seems to work.

**Comment by vincentfretin** [comment]
I fixed in https://github.com/plone/mockup/pull/1003

**Comment by mauritsvanrees** [comment]
FTR, fixed in https://github.com/plone/mockup/pull/1009, not 1003.
