### ISSUE TITLE
Exception mismatch between "zope.browserresource.directory" and "Products.CMFPlone.resources.browser.combine.get_resource"

### ISSUE THREAD

**Issue by d-maurer** [plone/Products.CMFPlone#3212]
## BUG
`zope.browserresource.directory` raises a `KeyError` in line 91 for a missing resource; `Products.CMFPlone.resources.browser.combine.get_resource` expects `NotFound` or `AttributeError` for a missing resource.

If the missing resource is encountered during portal construction for an extension profile, the portal construction terminates prematurely but the transaction is not aborted resulting in a portal that is only partially configured (and therefore partially disfunctional).

**Comment by fredvd** [comment]
This is a nasty issue where I think there are 2 different use cases.  :-(

I added one of the Exceptions in get_resource at the beginning of this year, because the bundling was too fragile: when only one resource from one add'on is missing, the bundling fails, no js is delivered and the developer is locked out from fixing anything through the resource registry control panel, because all JS is no longer served. 

so when you make one mistake in the control panel, you'r locked out and your site is/was destroyed beyond repair, unless you would manually fix configuration registry entries....

https://github.com/plone/Products.CMFPlone/issues/3096

One could argue that the resource registry should work independent of the Plone js delivered, but that's something given at the moment. 

But on programmatic/ profile creation, it's valid to have a full termination and  transaction abort in this bundling. 

I think this issue from Andreas Jung might also have something to do with this, but it has no feedback yet. https://github.com/plone/plonetheme.barceloneta/issues/224)

**Comment by d-maurer** [comment]
The bigger issue (compared to the exception mismatch) is actually that a portal can get created with missing configuration due to a missing resource. It has been this scenario which led me -- after quite some tedious analysis -- to the exception mismatch.  In my view, it was not a good idea to not abort in such a situation: rather than a clear local (near to the error point) error message, you get instead some strange error potentially much later on. If this were reverted, at least I could live with the exception mismatch.

Otherwise, either the exception raised by `zope.browserresource` should change or `KeyError` should be handled by `get_resource` along `NotFound, AttributeError`.

**Comment by jensens** [comment]
In Plone 6 the whole part was massively refactored to use `webresource` and the code in `combine.py` is gone.
