### ISSUE TITLE
Root level permissions can be accidentally removed in ZMI

### ISSUE THREAD

**Issue by ewohnlich** [plone/Products.CMFPlone#3223]
### Explanation
Plone sets some default roles related to Plone Site Setup in controlpanel/permissions.zcml pertaining to the Site Administrator role. However this role does not exist on the Zope root, it is only created for a Plone Site object. In the database, these permissions are still correctly assigned to the Site Administrator role, however the ZMI Security tab has no way to render this on the form because that role doesn't exist there. So when that form is submitted for ANY kind of change, the Site Administrator role will no longer be assigned. The Plone Site object relies on the "acquire" permission setting instead of directly assigning on the Plone Site object.

### What I did
Changed some security settings on the ZMI root unrelated to the Plone Site Setup permission suite.

### What I expect to happen:
No changes to the Plone Site Setup permission suite assignments.

### What actually happened:
Site Administrator was no longer assigned these permissions on any Plone site in this Zope.

### What version of Plone/ Addons I am using:
Plone 5.2.2

### Solutions
There are at least two possible changes that can address this. I don't know which is most appropriate.

1. Add the Site Administrator role to the Zope root. This should possibly be done for other Plone defined roles, for the same reason
2. Assign these permissions in the GenericSetup rolemap.xml

**Comment by mauritsvanrees** [comment]
I can imagine this going wrong, yes.
Least invasive would be the second solution. So add them to `rolemap.xml` and add an upgrade step in `plone.app.upgrade`.

I find it a bit surprising that non-standard roles can be specified in [`permissions.zcml`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/permissions.zcml). I always assumed you should only do the standard roles. But apparently it works, at least a bit.

For a new database I could imagine trying to add these roles in the Zope root, when adding the first Plone Site. Probably not when adding a second Plone Site or during migration. I think either `PlonePAS` or `PluggableAuthService` already replaces the entire root `acl_users` object, so that might be a reasonable place.

Note that add-ons may have the same problem for their own custom permissions. I would not want to advise add-on writers to add their roles in the Zope root. So I would not want to advise it for core Plone either.

So for me, `rolemap.xml` is the way to go. But maybe others have a different opinion?

**Comment by ewohnlich** [comment]
> Note that add-ons may have the same problem for their own custom permissions. I would not want to advise add-on writers to add their roles in the Zope root. So I would not want to advise it for core Plone either.

Agreed about rolemap.xml

The problem with adding an upgrade step is that a site might have already customized these permissions on the Plone site level. I know my company restricts most perms for Site Administrators so that they mostly can just do some basic settings and user/group management. I don't think there is a way to communicate some kind of optional step in portal_migrations about this? Maybe a more sophisticated upgrade step could be used where it only updates if the existing permission on the Plone level is unchanged.

**Comment by mauritsvanrees** [comment]
> Maybe a more sophisticated upgrade step could be used where it only updates if the existing permission on the Plone level is unchanged.

That could work and would be best. I don't know how hard that would be.

It is a corner case that not many people will bump into I guess. We could do this just in `CMFPlone` `rolemap.xml` so it works for new sites, and not change existing sites.
