### ISSUE TITLE
Build with parameters is gone in Jenkins

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3239]
I went to https://jenkins.plone.org/job/pull-request-5.2 to fire a build. Looked for the "Build with parameters" link but I could not find it.

**Comment by ale-rt** [comment]
CC @plone/testing-team 

As a workaround this worked: https://jenkins.plone.org/job/pull-request-5.2/buildWithParameters?PULL_REQUEST_URL=https://github.com/plone/plone.app.multilingual/pull/341

Note: I did not run trigger the whole build again with `jenkins-plone-org please run jobs` to not overload jenkins.

**Comment by gforcada** [comment]
It should still be there :) don't ask me why, but since a few Jenkins releases the usual links on the left column are gone and now they can only be found on the dropdown menu that shows up when you hover the package name:

![menu](https://user-images.githubusercontent.com/1155680/107535858-6eff0900-6bc1-11eb-93ac-a2b15a795e77.png)

**Comment by ale-rt** [comment]
Yes thanks :) 
It is also accessible with the direct link: https://jenkins.plone.org/job/pull-request-5.2/build?delay=0sec
