### ISSUE TITLE
Improve Mockup inlinevalidation, do only client side validation

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#3259]
The current situation of our form validation is like that:
For each ``blur`` event, that is when a form element looses focus, we're sending a request with the complete form values to the server and let it validate there. That includes the whole z3c.form widget extract machinery and so on. In case of an error, it's then displayed inline. We're ignoring ``input[type=file]``, so large binary data is not submitted. If we have a required file field, the validation will fail.

See: https://github.com/plone/mockup/blob/7278c5a97904993666f78da7e9f0949fd4d3b429/mockup/patterns/inlinevalidation/pattern.js#L205

That happens for each blur event of the input fields. The payload can be quite big for big forms with a lot of data. Also, in my experience the form validation gets always in my way and the UX feels very broken. E.g. you're editing a the first input, e.g. a ``title`` field. After leaving it all, each and every other required field turns red because they were not filled out yet.

**Proposed solution**
Let's switch to client side form validation only.
Out of the box, when using the correct input types the web browser form validation is quite good.
In patternslib we have a more comprehensive form validation which also allows validation in dependency of other form fields:
See: http://beta.patternslib.com/demos/validation

/cc @petschki as @agitator said you have an opinion here :)
Also /cc @frapell as you have an open issue in Mockup: https://github.com/plone/mockup/issues/905
And @m3g4p0p with https://github.com/plone/mockup/issues/973

**Comment by frapell** [comment]
@thet Yup, inline validation is not easy... unfortunately, I am not sure how you could bring the whole logic to do it client side. You can build a very complex form, with not only specific validators on fields for data that is only relevant for that field, but you can also create invariants where data from several fields are evaluated...

I cannot think of a good solution, other than to only do very simple inline validation, like whether a field is required or not and that you are entering numbers instead of characters, and nothing else, and then let the form come back after submit, if there are more complex validations erroring...

**Comment by m3g4p0p** [comment]
Yes by using semantic input types and constraint attributes where possible, we could already catch a lot of things on the client side. AJAX validation might still kick in though if a field appears to be valid otherwise, and only then check for more complex stuff such as schema invariants -- this would already save a couple of round-trips to the server (checking for missing values via AJAX is certainly overkill).

Also, having those constraints present in the templates would make it much easier to implement your own client side validation; we ended up extending the regular z3c field widgets for just this purpose, but that's quite a bit of boilerplate.

**Comment by petschki** [comment]
+1 for client side validation (with custom bs5 styling support)

**Comment by thet** [comment]
Done in mockup/es6 by using pat-validation.
