### ISSUE TITLE
Unwanted jobs when creating a new PR

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.CMFPlone#3318]
When we create a new PR we have github hooks that point to builds we are not using anymore, e.g. Plonme 6 on Python3.6.

I am wondering if we should run "Re-create GitHub commit hooks" here https://jenkins.plone.org/roboto/

**Comment by ale-rt** [comment]
CC @plone/testing-team

**Comment by mauritsvanrees** [comment]
I ran that command two months or so ago. I don't think it helps. I think it is in a mr roboto config file on the Jenkins server.
Oh, looking at the [live changelog](https://jenkins.plone.org/roboto/) (token needed), it seems someone is running the command now. I don't think this will solve it, but worth a try.

It does not look like anyone who is in the testing team on GitHub is actually still involved in Jenkins or mr.roboto.
@fredvd has access to the Jenkins machine, but he is unavailable at the moment. So maybe @gforcada can look, or someone on the @plone/ai-team.

The problem should be in [`WarnTestsNeedToRun`](https://github.com/plone/mr.roboto/blob/3fd95d071d62f30caf6d55028767cedbde651439/src/mr.roboto/src/mr/roboto/subscriber.py#L394-L397), that this somehow thinks the combination of Plone 6.0 and Python 3.6 is wanted.

The strange thing is that the roboto code that creates the Jenkins jobs based on the 'please run jobs' comment, [`TriggerPullRequestJenkinsJobs`](https://github.com/plone/mr.roboto/blob/3fd95d071d62f30caf6d55028767cedbde651439/src/mr.roboto/src/mr/roboto/subscriber.py#L591-L597) seems to do the right thing, running Plone 6 only on Py 3.7 and up. But the linked part that determines the Python and Plone version combinations looks the same as the other linked subscriber. A slightly different structure, but still.

It could be that the last subscriber actually *does* try to create a 6.0-3.6 job and that this simply fails silently because there is no such job. That would mean the mr.roboto config on the Jenkins servers needs to be updated.

**Comment by gforcada** [comment]
I will have a look, and yes re-creating the hooks does not help, it is a configuration setting.

**Comment by gforcada** [comment]
The configuration looks fine from a first glance... so it might be on the code side 🤔

**Comment by mauritsvanrees** [comment]
> I ran that command two months or so ago. I don't think it helps. I think it is in a mr roboto config file on the Jenkins server.
Oh, looking at the live changelog (token needed), it seems someone is running the command now. I don't think this will solve it, but worth a try.

The command is finished. I created a [PR on CMFPlone](https://github.com/plone/Products.CMFPlone/pull/3319) afterwards to test this. In the [roboto log](https://jenkins.plone.org/roboto/log?token=XXX) this is visible when you have the right token:

```
2021-09-15 10:56:21,747 INFO PR plone/Products.CMFPlone#3319: created pending status for plone 6.0 on python 3.9

2021-09-15 10:56:21,335 INFO PR plone/Products.CMFPlone#3319: created pending status for plone 6.0 on python 3.8

2021-09-15 10:56:20,958 INFO PR plone/Products.CMFPlone#3319: created pending status for plone 6.0 on python 3.7

2021-09-15 10:56:19,288 INFO PR plone/Products.CMFPlone#3319: changelog entry: error

2021-09-15 10:56:17,459 INFO COMMENT plone/Products.CMFPlone#3319-919830741: IGNORED as it is from mister-roboto

2021-09-15 10:56:15,772 INFO PR plone/Products.CMFPlone#3319: Contributors Agreement report: success

2021-09-15 10:56:13,309 INFO PR plone/Products.CMFPlone#3319: with action opened

2021-09-15 10:55:34,170 INFO Commit: not in sources - plone/Products.CMFPlone - nuke-trailing-whitespace do nothing

2021-09-15 10:55:33,100 INFO Commit: send mail: coredev push to Products.CMFPlone

2021-09-15 10:55:33,099 INFO Commit: on plone/Products.CMFPlone nuke-trailing-whitespace 37146fd3ab85614d911027667925faa2fcd4e423
```

So it says it created the 'pending' status for 3.7, 3.8 and 3.9. But in the checks of the PR there is a line:

    Plone Jenkins CI - pull-request-6.0-3.6 Expected — Waiting for status to be reported

![Screenshot 2021-09-15 at 11 00 14](https://user-images.githubusercontent.com/210587/133404081-91da87a6-277f-4d71-b07a-2f15cad64c3b.png)

Is this coming from somewhere else then? Ah, this is in the [branch protection rules](https://github.com/plone/Products.CMFPlone/settings/branch_protection_rules/8560).

![Screenshot 2021-09-15 at 11 02 39](https://user-images.githubusercontent.com/210587/133404378-851813e5-a10b-45c7-b8da-f6d789d54a01.png)

I have deleted 3.6 there, and have made 3.9 required like the others. That should fix it.

**Comment by gforcada** [comment]
@mauritsvanrees  cool that you found it, I was going nuts trying to see how mr.roboto was actually being able to create this 3.6 pending job!
