### ISSUE TITLE
missing site_description and display_pub_date_in_byline in ISite controlpanel

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#346]
the ``ISiteSchema`` in ``plone.app.controlpanel`` 2.3.x [1] defines two fields, which are missing in ``Products.CMFPlone`` ``ISiteSchema`` interface [2]:

- [ ] site_description: The site description is available in syndicated content and in search engines.
- [ ] display_pub_date_in_byline: Displays content publication date on site pages. (as per [PLIP 8699](https://dev.plone.org/ticket/8699))

[1] https://github.com/plone/plone.app.controlpanel/blob/2.3.x/plone/app/controlpanel/site.py
[2] https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/interfaces/controlpanel.py

/cc @tisto

**Comment by tisto** [comment]
Site description was removed because it was never used anywhere in Plone 4.3.x, not in syndicated content nor for search engines. https://github.com/plone/Products.CMFPlone/issues/139

I don't recall why or when display_pub_date_in_byline was removed though. 

I'd be ok with re-adding both settings if we actually implement the functionality and write robot tests for it.

**Comment by hvelarde** [comment]
@tisto @rodfersou is working on that, please guide him on how to write the tests you want.
