### ISSUE TITLE
Todo: Invalidate cache of webresource

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3505]
As discussed with @pbauer and @MrTango 

- provide utility function in `resources.utils.bundles_changed` to write timestamp (int) at Plone root to `_webresources_bundle_changed`.
- add value of `_webresources_bundle_changed` to cache hash of rendered resource viewlet
- add subscriber to `plone.registry` record lifecycle events and call above function if a prefix `plone.bundle...` changes.
- if in theme a "clear cache" is requested,  call above function.

**Comment by mauritsvanrees** [comment]
I like it.
Thise timestamp could also be used as value of the [`resourceRegistries` etag](https://github.com/plone/plone.app.caching/issues/93).

**Comment by jensens** [comment]
> * if in theme a "clear cache" is requested,  call above function.

Probably it is better if there (if there isn't already) is a event in `plone.app.theming` to subscribe to. Otherwise we may introduce circular dependencies...

**Comment by jensens** [comment]
In Resource Registry Control Panel we have the possibility to go to debug mode and back. I think this is no longer needed. Correct me if I am wrong (or re-open)

**Comment by MrTango** [comment]
What does that back and forth do for cache invalidation?

**Comment by jensens** [comment]
the hash is calcultated again, so a new url is used if the referenced file changed.

**Comment by fredvd** [comment]
@jensens How has the cache invalidation now been implemented? I checked Products.CMFPlone /resources but I cannot find anything that looks like "bundles_changed" or bundle_changed or how the cache works.

**Comment by jensens** [comment]
@fredvd The UniqueResourceTraverser `++webresource++SOMETHING` is registered w/o any specific functionality except it inserts the HASH to the URL. Hash calculation and URL generation is performed by webresource itself from the given file. If the file changes, the hash changes, so the generated URL changes.  Invalidation happens automatically. The development settings are only controlling the caching of the whole rendered viewlet, since rendering can be expensive due to hash calculation.

**Comment by mauritsvanrees** [comment]
@jensens What I am seeing now, is that in production mode the scripts and styles viewlets are cached in volatile attributes on the site root, and are not changed until a restart, or until you enable and disable debug mode.

So what happens when you install an add-on with an extra bundle?  Nothing:

- Install plone.session.
- No extra style link is added in the viewlet.
- Click debug mode.
- Bingo, the extra style is there.

I don't know if this is what you meant yourself when creating this issue. :-)

It would be nice if this worked without a Manager needing to remember to do this.  In Plone 5.2 we had an import step for this, that checked if `registry.xml` contained changes to the resource registries, and then combined bundles, or whatever it did.  Maybe something similar could be done in Plone 6?

**Comment by mauritsvanrees** [comment]
I think solving this would be a bugfix and does not need to wait until 6.1.  It *does* need careful consideration though.

I have created PR #3771.

**Comment by yurj** [comment]
My idea: https://github.com/plone/Products.CMFPlone/pull/3771#discussion_r1449094269
