### ISSUE TITLE
Removing expressions-patch breaks sites with skin templates in 6.0.0b1

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3581]
Removing `earlypatches/expressions.py` in 0de3c3c breaks sites with old skin-based templates.

I have a site that uses skin templates with `context/main_template/macros/master` and in 6.0.0b1 all of these are broken with `zExceptions.NotFound: zExceptions.NotFound: macros`

I'm not sure if we should force everyone to stop using add-ons that use such a pattern (or update them). Is there another way to fix these than to rewrite all skin templates to BrowserViews?

**Comment by pbauer** [comment]
Another example is a action `object/@@faceted_search_subtyper/can_disable` that fails with 
```
  File "/Users/pbauer/workspace/coredev/src/Zope/src/Products/PageTemplates/Expressions.py", line 109, in boboAwareZopeTraverse
    raise NotFound(name)
zExceptions.NotFound: zExceptions.NotFound: can_disable
```
Where `can_disable` is a property of the View `faceted_search_subtyper`.

**Comment by mauritsvanrees** [comment]
The patch was added as a workaround because a Zope security fix was too strict for Plone, causing problems like the above. In Plone 6 we should fix any underlying problems.
For the `main_template` we should allow access to the `macros` property. I am preparing a PR.
For `faceted_search_subtyper` a similar fix should be done, defining `can_disable` (and probably others) as fine to call from untrusted code.

It *is* better to rewrite all skin templates to browser views. In the documentation I may add a list of technologies that are deprecated, and this is one of them. But Plone 6.x should definitely still support them.

**Comment by pbauer** [comment]
Word of warning: This pattern only work with methods. If you use `@property` in a browser-view it cannot be accessed in a expression even when you try to allow it using `allowed_attributes` or `allowed_interfaces`.

**Comment by mauritsvanrees** [comment]
> Word of warning: This pattern only work with methods. If you use `@property` in a browser-view it cannot be accessed in a expression even when you try to allow it using `allowed_attributes` or `allowed_interface`.

Are you saying my fix in https://github.com/plone/Products.CMFPlone/pull/3583 does not work? I think it does. Maybe I only tested it in the custom skin where it works, and it fails for filesystem skin templates? Do you have an example?
