### ISSUE TITLE
Bug when discussion is enabled, the browser scroll down to the end of the page (6.0.0b1 classic)

### ISSUE THREAD

**Issue by phgv** [plone/Products.CMFPlone#3623]
When discussion is enable and the page is loading, the cursor focus on the text field of the comments and the browser scroll down to the end of the page.

### What version of Plone/ Addons I am using:
Plone 6.0.0b1 Classic

**Comment by karthiknadar1204** [comment]
I would like to work on this issue if it is still up for grabs,Please assign it to me @ericof @jensens

**Comment by mauritsvanrees** [comment]
I noticed the problem recently myself.  Does not look like anyone is working on it, so go ahead, it would be nice to get this solved.  Thanks for your interest!

**BUT**: please first read up on how to [contribute to Plone](https://6.docs.plone.org/contributing/index.html).  Among others, it explains that for legal reasons you need to sign the **Plone Contributor Agreement**, otherwise we cannot accept a contribution from you.
Especially read the [first time contributors page](https://6.docs.plone.org/contributing/first-time.html), which says: "Never ask to be assigned to an issue. Instead you may post a comment to claim it." :-)

**Comment by karthiknadar1204** [comment]
sure @mauritsvanrees , Thank you for the guidance.

**Comment by karthiknadar1204** [comment]
@phgv @mauritsvanrees I am exploring the project, could you please help me with showing where is the discussion link on the page https://plone.org/

Can't seem to find the link

Would love to make my first pull request to the project by completing this issue.
Thank you.

**Comment by phgv** [comment]
@karthiknadar1204, the website https://plone.org/ uses Plone 6 with Volto. The bug related to this issue can be found by installing a local instance of Plone 6 in classic mode and enabling the discussion feature in the settings.

If you have any questions, please let me know.

**Comment by mauritsvanrees** [comment]
Fixed with `plone.app.discussion` 4.0.3.
