### ISSUE TITLE
Edit action missing from toolbar when object is locked

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#3674]
### What I did:

Tried to edit an object, for which another user had the edit form open.

### What I expect to happen:

A message which tells me that the object is locked, because somebody is currently editing it.
An action to unlock it.

### What actually happened:

Edit action is missing from toolbar.

### What version of Plone/ Addons I am using:

6.0.0b3

**Comment by laulaz** [comment]
@MrTango IMHO it is good that the Edit action is removed on locked item, because you have the clear warning on the View :
<img width="1430" alt="capture" src="https://github.com/plone/Products.CMFPlone/assets/1101273/1d3d7bf6-6ce8-4361-a81b-b328330e8f21">

Perhaps I didn't understand the place you are in the site to "miss" this warning (?), IOW from where you are trying to edit the content.
Can you tell me more about this ?  because we need to work on another locking issue 😉

**Comment by petschki** [comment]
I would say this is a feature not a bug. You get warned and if you are allowed you can unlock and edit the page. Thats the intended behavior.

**Comment by MrTango** [comment]
you are right, the problem here was, that the message was missing because it is rendered in a separate part of the template, not like other portal messages and my Diazo config was missing this. Now it is clear ;).
