### ISSUE TITLE
TinyMCE release history

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#384]
First of all, could whoever has the rights to do so please activate the issue tracker in the https://github.com/plone/Products.TinyMCE repository?

I would like to understand the release process for Products.TinyMCE:

- The latest version on pypi is 1.3.8:  https://pypi.python.org/pypi/Products.TinyMCE/1.3.8
- In the github repo there is no tag or branch for this version, and in the commit log I don't see anything related to 1.3.8.  **How do I find out what changes went into this version?**
- (There is a tag for 1.3.7 in github:  https://github.com/plone/Products.TinyMCE/tree/1.3.7)
- Both in http://dist.plone.org/release/4.3-latest/versions.cfg and in http://dist.plone.org/release/4.3.4/versions.cfg the version pin for Products.TinyMCE is 1.3.8.  However, the zip file for Products.TinyMCE in http://dist.plone.org/release/4.3.4/ has a version number 1.3.7, and the same is true in http://dist.plone.org/release/4.3-latest/.  **Why this discrepancy?**
- (For comparison, the 4.3.3 release has Products.TinyMCE at version 1.3.6, both as a zip file and in versions.cfg.)

Thanks for any clarification!

**Comment by jensens** [comment]
Issue tracker is now activated!

**Comment by jensens** [comment]
Looks like the last release went wrong. https://github.com/plone/Products.TinyMCE/commit/8e3961019a8fdd8b99840c1fa69c19209a8ec52e is the pre-release commit. So the tag is missing. 

You can use github to see what changed, i.e. by looking at the commit history. https://github.com/plone/Products.TinyMCE/commits/1.3.x iirc theres is also a way on github to compare commits/tags/branches.

On PyPI there is a fine 1.3.8 zip file.

If 1.3.8 is the release http://dist.plone.org/release/4.3.4/versions.cfg points to it should be uploaded to http://dist.plone.org/release/4.3.4/ too, seems this is missing. By since PyPI has it its not a major problem.

**Comment by fulv** [comment]
Thanks, @jensens!
It's unfortunate that there is no tag for 1.3.8.
