### ISSUE TITLE
Available languages widget requiring selection

### ISSUE THREAD

**Issue by wesleybl** [plone/Products.CMFPlone#3841]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Available languages widget requiring selection, even after sending the languages from one box to another.

### What I did:

- I accessed the Language controlpanel. For example: https://classic.demo.plone.org/@@language-controlpanel
- Do not add any languages in Available languages.
- Click save.

### What I expect to happen:

- The form will be saved.

### What actually happened:

The form displays the validation message `Select an item from the list.`
This appears to be javascript validation, since no request is made.

![download](https://github.com/plone/Products.CMFPlone/assets/3297795/f09c567f-c6af-4853-be2a-64808941df8b)

### What version of Plone/ Addons I am using:
Plone 6.0.6 (6017)
CMF 3.0
Zope 5.8.3
Python 3.11.1 (main, Dec 7 2022, 01:11:34) [GCC 11.3.0]
PIL 9.5.0 (Pillow)
WSGI: On
Server: waitress 2.1.2

**Comment by wesleybl** [comment]
@petschki @thet is this something from the mockup?

**Comment by wesleybl** [comment]
@petschki would it still be a problem if someone unchecked all or items in the right box?

**Comment by petschki** [comment]
If you uncheck all values from a required orderedselectfieldwidget `pat-validation`shows the message above immediately and you cannot click the save button (in 6.0.6 cancel button is also disabled, but that got fixed in mockup also some time ago). This widget is based on a very old `z3c.form` template and JS implementation which is pretty outdated (see also https://github.com/plone/plone.app.z3cform/issues/184) and I would be happy to see a better implementation than this (eg. AjaxSelectWidget like the keywords field uses ... )

**Comment by wesleybl** [comment]
Yes. It shouldn't be necessary to select an item. The box itself is the selection. Thanks!
