### ISSUE TITLE
Options to create Folder not listed in `Plone 6.1.0a5.dev0 (6104)`

### ISSUE THREAD

**Issue by rohnsha0** [plone/Products.CMFPlone#3996]
### What I did:

I have installed plone using `buildouts.coredev` (in development mode) with newly released `Plone 6.1.0a5.dev0 (6104)`. When attempting to create folder.. I find no options whatsoever to create a folder.
![image](https://github.com/user-attachments/assets/0a16d3d0-f01c-44ba-a1bf-fa5163c1be9d)

### What I expect to happen:
Folder to be in the list 

### What actually happened:
No ways to create a folder

### What version of Plone/ Addons I am using:
```
Plone 6.1.0a5.dev0 (6104)
CMF 3.5
Zope 5.10
Python 3.11.2 (main, May 2 2024, 11:59:08) [GCC 12.2.0]
PIL 10.2.0 (Pillow)
WSGI: On
Server: waitress 2.1.2

```

**Comment by davisagli** [comment]
This is not a bug. In order to use folders, make sure you create your Plone site using the "Create Classic UI Plone site" button.

<img width="1014" alt="Screenshot 2024-08-06 at 7 56 26 AM" src="https://github.com/user-attachments/assets/d22778b0-acce-490b-9179-b731216e48d3">

The "Create a new Plone site" button installs plone.volto, and Volto does not use folders. (Every page can be a folder in Volto.)

**Comment by rohnsha0** [comment]
ah... misinterpret those options.. thanks @davisagli
