### ISSUE TITLE
Release mockup and update versions.cfg

### ISSUE THREAD

**Issue by ebrehault** [plone/Products.CMFPlone#410]
The Plone 5.0b1 versions (http://dist.plone.org/release/5.0b1/versions.cfg) contains `mockup=2.0.0`, and there is no mockup 2.0.0 release.
So it breaks buildout.
We probably should release mockup 2.0.0, but actually I think we do not need mockup at all in the distribution (as it is just used to generate bundles that are then delivered by other packages like Products.CMFPlone or plone.app.wigets, so that's required only for development).

**Comment by vangheem** [comment]
We still need mockup python package distribution to go into dev mode on a Plone 5 site so it's still a dependency.

I just tagged version 2.0.2 and updated the mockup MANIFEST.in to properly include the correct files.

@esteele @timo I do not have pypi rights to make a release of mockup. Could you grant me rights or make a release and update the version requirement we're using?

**Comment by ebrehault** [comment]
Ah yes, right, mockup declares some resources we need in dev mode. I forgot that.

PS: so, as mockup is a dependency we need anyway, would it make sense to let all the bundles directly into mockup instead of copying them into different packages ?

**Comment by vangheem** [comment]
I think the preference is that mockup have all the source base javascript and then all the packages in plone that depend on a javascript "bundle" will include them in their own packages but it seems some have differing opinions on this.

Including bundles in the packages that use them gives developers multiple examples of how to use mockup.

@bloodbare might have some thoughts also.

**Comment by esteele** [comment]
@vangheem: You have pypi rights now.

**Comment by vangheem** [comment]
Thank you. Released. I also upped the coredev mockup version to 2.0.2

**Comment by vangheem** [comment]
What is the process of updating http://dist.plone.org/release/5.0b1/versions.cfg ?

**Comment by bloodbare** [comment]
Using an example may help to undestand.

* There is a python module that adds some awesome functionality that needs some js library and its wrapped inside a mockup pattern. Then the package must have the js library in its namespace (loaded with bower or not), the source of the pattern and a bundle to distribute the compiled version. It can be compiled with the helper scripts of plone or with its own Grunt*. If it wants to use its own grunt* it will need to have a mockup (a bower definition to get the mocku)p but its not needed to checkin on the package as its already on the namespace of plone if it wants to execute in dev mode on the site. If it wants to be optimal its own grunt* can exclude all packages that are in plone already. It it wants to use the plone scripts it will not need to have mockup as its served on plone.

As we have the require_bundle helper to add a specific bundle on a specific view we can load a bundle on a specific browser view, so that heavy js plugin its only loaded when its needed.

For example, if collective.datagrid wants to have the datagrid plugin of jquery it can define a bundle that loads all the needed js from datagrid with its specific mockup pattern in a specific bundle and the code can be in the same package, so it defines the bundle in registry, it has the js library and maybe a gruntfile to create a bundle version (and in this case mockup and mockup-core are dependencies of bower.json that are loaded only to compile and not checked in).

What we have on the mockup repo in my opinion is the basic mockup patterns that are used on plone and we treat them different than a external js library because development is in Plone community joined to Plone development. We could treat mockup as we treat bootstrap or any other js library, but that would mean that dev is out of plone. 

This is just a fast opinion, maybe I'm missing something or I didn't understood the question!

**Comment by esteele** [comment]
I've taken care of it.
