### ISSUE TITLE
Still issues with plone legacy bundle in Plone 5.0b1

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#414]
I have still issues getting a Plone 4.3 packages with all JS resources working under 5.0b1 without configuration changes (which is obviously the goal of the Plone legacy bundle).

I added 'xmldirector.plonecore' to a recent buildout.coredev checkout and installed the XML Director profile, added a new Dexterity content-type with one additional field of type "XML Text" (provided by XML Director).

Adding a new instance of the new type gives me the following JS error on the console:

![screenshot 2015-04-07 14 31 18](https://cloud.githubusercontent.com/assets/594239/7023144/1177ce20-dd33-11e4-8207-3ecc0e7728cb.png)

The ace.js is part of the legacy bundle:

http://www.awesomescreenshot.com/image/43456/25e6cba9d46c52f471cfcec7034084a4

Related jsregistry.xml:

https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/profiles/default/jsregistry.xml

**Comment by vangheem** [comment]
I tested. The problem seems to be a problem with how the ace build works. The ace-builds/src-min/ace.js uses a require call to add the window.ace object. If requirejs is not used(plone 4), this is set immediately.

To fix this, I've created a pull request for you to review: https://github.com/xml-director/xmldirector.plonecore/pull/3

An example of this being done in plone core is here: https://github.com/plone/plone.app.registry/blob/master/plone/app/registry/browser/resources/registry.js

I am going to close this issue. Please re-open if I misunderstood.

**Comment by zopyx** [comment]
Is such a change compatible to local.js compatible with Plone 4.3?

**Comment by vangheem** [comment]
Yes, it should work but is untested on plone 4.3. It first checks if require is defined. If it isn't, it creates a shim "require" method to use(there is other shim require js code that might do this even better--just a quick fix example).

**Comment by zopyx** [comment]
Ok, will check it out

2015-04-08 7:13 GMT+02:00 Nathan Van Gheem <notifications@github.com>:
