### ISSUE TITLE
portal_catalog returns wrong results when batching with specific sort

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#441]
while working on an issue with plone.app.collection i stumbled across this weird behavior of portal_catalog.
- in a Plone 4.3 site i created 12 content items (events) in the event folder with id 1-12.
- i modified the collection to have a batch size of 5 (and removed all constraints except that event types should be searched)
- i placed a pdb in plone.app.querystring.querybuilder on line 156, directly after the catalog call to investigate the problem.
- i set sorting for modification date.

so, now i got a result set spread over 3 batching pages. the first two pages are fine (1,2,3,4,5 and 6,7,8,9,10). the 3rd page shows 6,7 instead 11,12.

when sorting for something else (e.g. sortable title), the 3rd page shows correctly 11,12.

here is a query without batching and sorting on created. correct results:

```
>>> parsedquery
{u'portal_type': {'query': [u'Event']}, 'sort_on': u'created', 'sort_order': 'ascending', 'path': {'query': ['/Plone/']}}
>>> [it.id for it in catalog(**parsedquery)]
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
```

here is a query with batching and sorting on created, showing the last batch

```
>>> parsedquery
{'b_size': 5, u'portal_type': {'query': [u'Event']}, 'sort_on': u'created', 'sort_order': 'ascending', 'b_start': 10, 'path': {'query': ['/Plone/']}}
['6', '7']
```

here is a query with batching and sorting on Sortable Title, showing the last batch:

```
>>> parsedquery = {'b_size': 5, u'portal_type': {'query': [u'Event']}, 'sort_on': u'sortable_title', 'sort_order': 'ascending', 'b_start': 10, 'path': {'query': ['/Plone/']}}
[it.id for it in catalog(**parsedquery)]
['11', '12']
```

**Comment by fredvd** [comment]
I'm not sure if a recent bug I experienced is similar, but I'll list it here anyway: If you sort in a collection on a date where some results don't have any value, the batching gets confused as well.

If batching is turned off in such a collection the items with no Date are not returned at all. If you enable batching, the last batch page will miss/truncate the number of items that had the empty sort key, but it results in items not being displayed that DID have a sortable date, but ended up being last. so if you have 70 items retuned of which 5 have no valid expiration date, batching on batch size 30 will give you 30 30 15 batch results. Weird. 

Off couse the tricky part is what a collection should return anyway if you sort on 'unsortable' items like empty fields, should they return at all (now not the case), should they be inserted at the top or be appended at the bottom? 

I was thinking of adding a small examples to plone.app.contenttypes testcase to demonstrate the problem using the expiration dates as this is about the only field that can be empty and be sorted on.

**Comment by mauritsvanrees** [comment]
@fredvd When you say '30 30 15' batch results you mean '30 30 5' I think? So five results too few instead of five results too many.

**Comment by fredvd** [comment]
@mauritsvanrees You are right, I meant 30 30 and then 5 in the final batch. Don't calculate on friday afternoons :-P . Fixed my comment.

**Comment by hannosch** [comment]
Just some tips for debugging:

* A date index only stores information with a 1-minute granularity, so if you quickly create many items, they might all have the same value, so a sorting order isn't actually deterministic.

* A date index does not contain items which have no date, i.e. None as the date value. If you sort on something, the result will not contain items which aren't in the sort index.

* The catalog does an optimization when you sort and batch at the same time. If you try to access a batch from the second half of the result set, it doesn't forward sort everything. Instead it reverse sorts the result set until it finds all the items it needs for the requested batch, and at the end reverses the list again.

* The combination of the first and last point might mean that you get an undefined / unstable sort order and the exact result set depends on the exact execution path taken. Since the path is different, you might get a different result.

To fix this, I'd upgrade to ZCatalog 3+ and define a combined sort_on using `created, getId`. The getId part should make the result order stable, even if the date part isn't.

Another approach might be to change the ZCatalog code and internally change any sort_on query to sort on the internal catalog record id as the last sort criteria, in addition to all user specified values. That should introduce a stable order, even if the original query isn't. But that comes with some additional overhead.

**Comment by pbauer** [comment]
@hannosch thanks for the wisom :beer:

**Comment by thet** [comment]
while searching for old issues to close, this one is just too old to keep open.
sorry for stealing time from anyone here.
