### ISSUE TITLE
plone.folder.interfaces.IFolder blacklisted for object_provides

### ISSUE THREAD

**Issue by thet** [plone/Products.CMFPlone#446]
@hannosch added a ``BLACKLISTED_INTERFACES`` for the object_provides catalog index in commit: https://github.com/plone/Products.CMFPlone/commit/04bc94cb2b70529a419c4b8b2a27a65d7e597dc5
The list contains ``plone.folder.interfaces.IFolder``. What's the reasoning behind this? I'd have found it convenient to search for IFolder in object_provides and get AT and DX and whatever contenttype is folderish in the results.

**Comment by hannosch** [comment]
At the time, the is_folderish catalog index was the canonical way of looking for all folderish types. This was the way to get to all folderish types across basic Zope, CMF, AT and any other type systems. There were a bunch of interfaces across all of these which were called IFolder/ish, but were only implemented by a subset of all content classes.

So the blacklist removed the duplicated and non-canonical bits to save space and avoid the confusion. Maybe things have changed by now. I guess IPrincipiaFolderish might still be the most basic equivalent of the pre-interfaces is_folderish marker attribute.

**Comment by thet** [comment]
@hannosch ok, that makes perfectly sense, thanks for the explanation. First I was wondering an expecting any Interface, an object provides to be in the index. But indexing performance is a good reason for the blacklist.
``is_folderish`` is still the way to search for folderish items. Personally I like the object_provides more, as it is a generic way to search for anything.

**Comment by hannosch** [comment]
Yeah, when we started introducing interfaces for everything, we unfortunately introduced a whole lot of tiny or often meaningless marker interfaces. Many of those don't actually promise any real contract or API. The ones I put manually on the blacklist where some of the most notorious at the time. I always wanted to turn this into a whitelist instead, so you'd have to explicitly choose what to index, but never got around to it.

Since each index has both an forward and reverse index, that list of interfaces ends up being stored as strings for each content item. So there's a BTree mapping each interface name to each record id, and a BTree mapping each record id to a list of interface names. That ended up being somewhere in the 5-10kb range for just these interfaces, which was often bigger than the actual content of any item.

**Comment by thet** [comment]
Interesting details! I'm a big fan of the object_provides index, but I wasn't aware of this drawback...

**Comment by gforcada** [comment]
I'm using it *a lot* actually... if we start cleaning up interfaces which are meaningless then maybe it will not be so bad.

We could also make the interfaces itself declare if they are internal or public, so only public interfaces are indexed (and by default make all interfaces internal)...

**Comment by davisagli** [comment]
Or we could make a type of index that stores a separate forward & reverse mapping of interface name to an incrementing integer, so that the real index can store integers instead of interface name strings. This would mean an extra lookup so we'd have to benchmark the effect on performance, but it would definitely save space in the database & in memory. I've always wondered why KeywordIndex doesn't work like this. I guess it's similar to how ZCTextIndex works with a separate lexicon of words, only for KeywordIndex we don't want the terms split into words.
