### ISSUE TITLE
Plone legacy bundle: further backward compatibility issue

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#479]
Related to 

https://github.com/plone/Products.CMFPlone/issues/428

Aceditor under Plone 5.0b1 tries to reload some supplementary resources through an improper URL
(see screenshots).

The solution seems to be to base the download path for resource explicitly  to ACE as documented here:

https://stackoverflow.com/questions/18346875/how-to-keep-ace-from-looking-for-themes-and-modes-in-current-directory

What would be the canonical path for stuff stored within the Plone legacy bundle and what would be the canonical way to determine if a some JS code is executed under Plone 4.3 or 5.0?

Plone 4.X
![screenshot 2015-05-03 11 34 05](https://cloud.githubusercontent.com/assets/594239/7444563/7a671f3a-f188-11e4-914b-a842370a4e08.png)

Plone 5

![screenshot 2015-05-03 11 34 00](https://cloud.githubusercontent.com/assets/594239/7444562/7a66580c-f188-11e4-97ce-af2d1287408f.png)

**Comment by vangheem** [comment]
To check if plone-legacy bundle is present, you can do something like this::

```
$('[data-bundle="plone-legacy"]').length > 0
```

Then, for you to be able to set the path of your ace editor resources, do something like:

```
ace.config.set("basePath", $('body').attr('data-portal-url') + "/Scripts/FullPathToMy/AceEditorDirectory");
```

In your case, you could just check for the presence of data-portal-url and always set the basePath when it was present. I suppose the reason these things works more often than not before was because of acquisition magic.

**Comment by zopyx** [comment]
Thanks, it works.
