### ISSUE TITLE
Move buildout.coredev Zope/CMF sources.cfg from svn.zope.org to github.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#647]

**Comment by gforcada** [comment]
Are all sources already moved from svn to github?

**Comment by pbauer** [comment]
All our checkouts except Products.ExternalEditor and z3c.formwidget.query are on github.

I dit not check if all packages from http://dist.plone.org/versions/zopetoolkit-1-0-8-zopeapp-versions.cfg, http://dist.plone.org/versions/zopetoolkit-1-0-8-ztk-versions.cfg and http://dist.plone.org/versions/zope-2-13-22-versions.cfg are on github.

**Comment by gforcada** [comment]
According to http://svn.zope.org P.ExternalEditor hasn't had any change since 3 years and there's a copy at @do3cc of it  https://github.com/do3cc/zope/tree/master/Products.ExternalEditor.

We need to make a copy of it on its own repo as jenkins jobs are already failing due to svn://svn.zope.org not being reachable (at least from jenkins.plone.org) http://jenkins.plone.org/view/All/job/docs-package-styleguide/21/console

**Comment by do3cc** [comment]
This is not a real copy. It is a full copy of the complete zope svn repo as one single github repo

**Comment by mauritsvanrees** [comment]
Everything is on github, in either the zopefoundation, collective or plone organizations.
