### ISSUE TITLE
Formatting for Event Listing

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#657]
Reformat event time
remove "." after numeric dates
"Mo" for month is not needed
![events my plone 5 site 2015-06-29 11-44-28](https://cloud.githubusercontent.com/assets/7101218/8411899/5b2d53de-1e54-11e5-8651-fd52d58c87de.png)

**Comment by tisto** [comment]
@3dogMcNeill thanks for reporting! :)

Is this Plone 5? Please use the Milestone setting in the right column to mark the Plone release.

**Comment by 3dogMcNeill** [comment]
@tisto aha! Yes, Plone 5. Will do, thanks!

**Comment by pbauer** [comment]
Do we want to use event_listing as the default_view for the aggregator at /events?

**Comment by pbauer** [comment]
I just talked to @sneridagh about that and we want to fix the design issues and propose to use it as the default-view for the Event-collection.

Todos:
- Create a improved mockup (we'll  ask @albertcasado)
- Move all styles to barceloneta and implement changes 
- Inspect possible accessibility issues (@polyester might have a look)
- Change the default event-collection to contain all events (not only future) since users can use the 'facets' in the event_listing

**Comment by thet** [comment]
+1!
Plus:
- use the HTML5 ``<time>`` element for datetimes
- cleanup semantic annotations (see: https://github.com/plone/Products.CMFPlone/issues/677 )

**Comment by agitator** [comment]
after discussion with @sneridagh we came up with following changes:
- unify template style with barcelonetta and summary_view styles
- get rid of month/week/day "filter" since they are not a real "month/week/day"-view in favor of a simpler future/past listing

see https://github.com/plone/plone.app.event/pull/194 for details


todo:
- update markup for HTML5

future:
- faceted search or similar would be nice
- real month/week/day views

**Comment by thet** [comment]
I've created https://github.com/collective/collective.portlet.collectionfilter which can be used for faceted search on catalog indizes on catalog types.

**Comment by pbauer** [comment]
the pr is merged.
