### ISSUE TITLE
review and possibly pick more obvious icons for toolbar and control panel

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#740]
@plone/ux-team @bledwell and I are looking at these now specifically for portlet management, display menu, and state

**Comment by tkimnguyen** [comment]
For portlet management we like http://fontello.com/#search=sweden 

![messages image 1084822621](https://cloud.githubusercontent.com/assets/815418/8780463/b4d157e8-2ece-11e5-96dc-b7efb2c2c7dc.jpeg)

**Comment by tkimnguyen** [comment]
For the display menu we like the last one shown here: http://fontello.com/#search=popup

![messages image 749887468](https://cloud.githubusercontent.com/assets/815418/8781034/6cd2a8d0-2ed2-11e5-92ff-832e0de6bce4.jpeg)

**Comment by davilima6** [comment]
For portlet I prefer ![captura de tela 2015-07-20 as 16 00 51](https://cloud.githubusercontent.com/assets/422130/8784462/a2e48a9e-2ef8-11e5-90a8-c69bf036862b.png) because Sweden's irregular shapes add unneeded specific (hierarchical) meaning. Or it could also be ![captura de tela 2015-07-20 as 16 01 15](https://cloud.githubusercontent.com/assets/422130/8784463/a2e94dd6-2ef8-11e5-891b-6c5467172445.png) if we prefer to hint on what actually a portlet is (a configurable box of content, generally with a header and a body). Ideal would be option (1) but with one column only, which represents better the provided functionality.

For Display menu I'd stick to current choice since the one above is already too much associated with popup and open in new window behaviors. Ideal would be a horizontal deck of cards/rectangles with one of them selected, raised above the others.

**Comment by agitator** [comment]
i also would leave the display menu for now - the proposed popup-icon looks like "duplicate" for me


the "sweden" doesn't have any similarity with a portlet, i also wouldn't use the settings-icon, since it has a complete different visual style

possible alternatives for the portlet 
![screen shot 2015-07-21 at 13 39 22](https://cloud.githubusercontent.com/assets/365761/8799907/316c1326-2fae-11e5-91da-a2844e15bc0b.png)
![screen shot 2015-07-21 at 13 38 59](https://cloud.githubusercontent.com/assets/365761/8799908/33390eac-2fae-11e5-92b8-79dd3042d3ff.png)

**Comment by jensens** [comment]
imo second one by @agitator is nearest to what i would say can be associated with a portlet

**Comment by djay** [comment]
There are some good icon suggestions for the toolbar in https://github.com/plone/Products.CMFPlone/issues/802

**Comment by agitator** [comment]
also would welcome the use of @enzus display and portlet icon, are we "free" to use them? what's their origin?

**Comment by davisagli** [comment]
The icons were updated in Plone 6
