### ISSUE TITLE
plone.app.iterate - Could we possibly allow renaming of checkouts to be a working feature?

### ISSUE THREAD

**Issue by neilferreira** [plone/Products.CMFPlone#744]
This was initially brought up in 2011 on the issues page, see https://plone.org/products/iterate/issues/31

Would this be a feature that could be easily supported?  A colleague of mine has attempted to look into it and it looks like dexterity will make this extraordinarily difficult.

**Comment by vangheem** [comment]
This is an odd use-case and it seems way too dangerous from a programming and user perspective to ever want to implement.

The short name(id) of the object is already changed when you check out an object so you'd need to track if the check out was changed the initial checkout. Then on check-in, you'd need to make sure the new id is not already take, if it is(then what?). Additionally, if you had that object set as a default view on a folder, you'll need to reassign that otherwise it'll be broken.

Moreover, I wonder if this would scare users who wouldn't expect renaming/moving their working copies to actually rename the original when they checked it back in.

You could try providing a PR put I'm inclined to close this issue as "won't fix".

**Comment by hvelarde** [comment]
:+1: on @vangheem
