### ISSUE TITLE
Fields from plone.app.user show up in dexterity schema editor.

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#768]
![screen shot 2015-07-31 at 10 08 23](https://cloud.githubusercontent.com/assets/365761/9003229/7cbdd1c8-376c-11e5-9a40-8726de9419ac.png)

**Comment by jensens** [comment]
and btw here its not possible to add those.

**Comment by pbauer** [comment]
The issue comes from plone.app.user: The fields from ``plone.app.users.schema.IUserDataSchema`` show up here and (I think) they should not. The field "Full Name" has the same issue. Of the two email-fields only the first one (E-mail) results in errors. The second (Email) works fine. 

The first one results in a traceback:
```
2015-08-16 20:11:43 ERROR Zope.SiteErrorLog 1439748703.120.295218487358 http://localhost:8080/Plone/dexterity-types/Link/@@add-field
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module z3c.form.form, line 242, in handleAdd
  Module z3c.form.form, line 250, in createAndAdd
  Module plone.schemaeditor.browser.schema.add_field, line 86, in add
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.dexterity.serialize, line 23, in serializeSchemaContext
  Module plone.supermodel, line 40, in serializeModel
  Module plone.supermodel.serializer, line 103, in serialize
  Module plone.supermodel.serializer, line 69, in writeField
ValueError: Field type plone.app.users.schema.ProtectedTextLine specified for field somefield is not supported
```

**Comment by ebrehault** [comment]
@pbauer I made a fix here https://github.com/plone/plone.app.dexterity/pull/178 but I cannot merge because I get a robot error http://jenkins.plone.org/job/pull-request-5.0/235/testReport/junit/Products.CMFPlone.tests.test_robot/RobotTestCase/Scenario_When_page_is_linked_show_warning/
I do not think it is related to my fix but as you changed this robot test recently maybe you have an idea about what is going on.

**Comment by pbauer** [comment]
That robot-test is unstable (probably a timing issue). The screenshot shows that all is well. I will fix it soon.

**Comment by zopyx** [comment]
Reopening this issue because the fix breaks the compatibility with Plone 5 and third-party Dexterity fields from Plone 4 to Plone 5.


https://community.plone.org/t/custom-dexterity-content-types-show-up-in-plone-4-not-in-plone-5/1957
https://github.com/plone/Products.CMFPlone/issues/1533

**Comment by thet** [comment]
The fields in ``plone.app.users.schema.IUserDataSchema`` are created with the ``plone.app.users.schema.NonEditableFieldFactory``. See https://github.com/plone/plone.app.users/blob/master/plone/app/users/schema.py#L50
IMO, all those ``ProtectedTextLine`` and ``ProtectedEmail`` fields should not be shown in the TTW editor, instead of using the hardcoded ``ALLOWED_FIELDS`` whitelist.

**Comment by gforcada** [comment]
I guess @tkimnguyen didn't want to close this... github interactions are scary every now and then: a forked (tkimnguyen) project (plone.app.dexterity) can close an issue (this one) in an unrelated project (Products.CMFPlone)... :-/

**Comment by tkimnguyen** [comment]
@gforcada wow sorry! This is really weird because I don't recall even reading about this issue, much less having a fork of it, pushing something to my fork, and then closing the issue... WTF

**Comment by tkimnguyen** [comment]
OK I had fixed some typos in my fork of the Dexterity docs https://github.com/tkimnguyen/plone.app.dexterity/commit/40058492babd5de8db82368c1e4b503ff4ad8abe ... no idea how that ended up committing plone.app.user fix & closing the issue.

**Comment by jensens** [comment]
Is this still an issue?

**Comment by ale-rt** [comment]
It does look like it is fixed to me (full name is not there any more):
![image](https://user-images.githubusercontent.com/1300763/86232906-f1880a80-bb94-11ea-8f41-6d902d45ea89.png)
If there is something else left I would open a more specific issue.
