### ISSUE TITLE
Turning off "Generate tabs for items other than folders." has no effect on pages, events ...

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#785]

**Comment by pbauer** [comment]
During the migration of the navigation-controlpanel that got lost. The registry-value set in is `nonfolderish_tabs`, but the navigation checks for a site_property called `disable_nonfolderish_sections`. In Plone 4 the setting nonfolderish_tabs was set to change said site_property but that functionality is gone. It could be fixed by having the navigation check if `nonfolderish_tabs` is False.

But: Is that setting actually useful? I would expect that being able to select which types should appear is enough since you can create the same results with more control. Sometimes you maybe don't know which of types are folderish and which are not. I'd consider removing it completely.

**Comment by hvelarde** [comment]
+1 makes sense

**Comment by pbauer** [comment]
Fixed (not removed) in 938d68c733be49ba84f8c6ec7508f0ce29f4b39d
