### ISSUE TITLE
Grammar fixes to "Insert Image" box

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#787]
1. Change "Just drag N drop files on the area below or press the "browse" button" to "Drag and drop images from your computer on the area below or click the "browse" button"

2. Change "Upload to... If nothing selected files we be added to current context" to something like "Upload to: Select folder or leave blank to add to current content item" 

3. Is the "Upload to" functionality really needed here? It's confusing that an image can be added here but also somewhere else (yes, I know that's not what's happening but it seems like it and that's the confusing part)

![imagebox jpg](https://cloud.githubusercontent.com/assets/7101218/9046715/b2cd760c-39fa-11e5-8f3a-3fbb479aedd2.png)

**Comment by jensens** [comment]
I would say this is related to #784

**Comment by tkimnguyen** [comment]
1. Changed to 'Drag and drop files from your computer onto the area below or click the "Browse" button.'

2. Changed to 'Select another destination folder or leave blank to add files to the current location.'

3. It is useful to be able to select a different destination folder, otherwise you have to cancel out what you're doing, navigate elsewhere, and only then upload files.

Changes made in PR https://github.com/plone/mockup/pull/544
