### ISSUE TITLE
Bring back image transforms tab

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#804]
refs. #796 

![selection_002](https://cloud.githubusercontent.com/assets/341393/9093655/b2f1498a-3b83-11e5-9cdb-e2d229499d0a.png)

**Comment by bledwell** [comment]
In my view rather than have a tab, Id have all the editing features immediately available. After all the user has already clicked on the "edit" tab. I think they should be able to make the changes without the transform tab (keep the options) but move them upfront. I doubt it can make Plone 5 but I think it should be there.

**Comment by jensens** [comment]
After auto rotation is implemented and plone.app.imagecropping as an addon works fine in 5.1, I close this one.
