### ISSUE TITLE
Non-folderish content types at the root level don't appear selected in the main navigation

### ISSUE THREAD

**Issue by enzus** [plone/Products.CMFPlone#830]
If you go to: http://dev.brianledwell.com:8081/Plone/image.jpg/view

the image won't appear as selected on the main navigation bar even if it's on the root level. It appears to be an intended behaviour for non folderish content types but I'm not sure it's the correct behaviour?

@plone/ux-team

**Comment by enzus** [comment]
Sorry just realised that this one is probably related to #785 
Delete it if that's the case.

**Comment by pbauer** [comment]
In don't think it is related.

**Comment by pbauer** [comment]
``plone.app.layout.viewlets.common.GlobalSectionsViewlet.selectedTabs`` compares `action_path` (`/myimage.jpg/view`) to the last part of `request['URL']` (`/myimage.jpg/image_view`). Since hey are not the same the navigation picks the fallback. That was introduced in https://github.com/plone/plone.app.layout/commit/d1f921d4f6a9a2a81ded4439c54a12503f52b381

**Comment by rmu75** [comment]
It seems this fix does not work correctly with multilingual sites.

**Comment by erral** [comment]
This fix breaks indeed all "INavigationRoot" enabled sub-sites (including the multilingual-enabled ones) because the "selected" portal_tab is not correctly calculated after this changeset.

With the previous code it worked for INavigationRoots, but it didn't for images, there was no test to show that, I have just added them:

https://github.com/plone/plone.app.layout/pull/65

**Comment by jensens** [comment]
From what I can see this was solved long time ago in https://github.com/plone/plone.app.layout/pull/69
