### ISSUE TITLE
Can't create mutiple plone sites

### ISSUE THREAD

**Issue by djay** [plone/Products.CMFPlone#838]
The simple front screen looks great and will display multiple websites when you have them but doesn't allow you to create more than one site. It also doesn't provide instructions on how to map your site to a url.

**Comment by pbauer** [comment]
Fixed in https://github.com/plone/Products.CMFPlone/commit/e5738436aecd6333a1952d32c3eac3cd40865599

Regarding the instructions: There are multiple methods to map sites to urls (apache, nginx, http://localhost:8080/virtual_hosting/manage_main). IMHO such instructions should live in the docs, not in the application.
