### ISSUE TITLE
Date-Time widget has broken layout

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#891]
![screenshot-dev1 veit-schiele de 8081 2015-09-09 07-57-34](https://cloud.githubusercontent.com/assets/594239/9754357/9a454930-56c8-11e5-84c7-41a90baaa3b4.png)

**Comment by hvelarde** [comment]
also, the position of the arrows to navigate to previous and next months is weird.

**Comment by davilima6** [comment]
I confirm all but scrollbar issues also in English and pt-br.

**Comment by ichim-david** [comment]
The problem comes from the pickdate.plone customizations from plonetheme.barcelonata which bumps up the font-size and adds the blue >>.
I suppose the the theme author wanted to style differently the arrows but right now both are enabled.
Look how the original pattern is styled with the black arrows and with no overflow scrolls:
http://plone.github.io/mockup/dev/#pattern/pickadate

**Comment by ichim-david** [comment]
I am quite confused of how we handle translations for widgets since right now the date widget can have 3 sources where it can get translated content: 
1.  canonical pattern option for the date widget comes from plone.app.widget.utils get_date_options
https://github.com/plone/plone.app.widgets/blob/master/plone/app/widgets/utils.py#L49
2. mockup/patterns/pickdate/pattern.js - uses translate module as such we have code like:
<pre>placeholderDate: _t('Enter date...')</pre>
3. pickadate library has translations in over 40 languages for all of these options and yet I don't see plone loading any of them.

Safest bet would be to continue to add to the get_date_options code as such
<pre>
            'today': translate(_plone(u"Today"), context=request),
            'clear': translate(_plone(u"Clear"), context=request),
            'close': translate(_plone(u"Close"), context=request),
</pre>
in order to get the widget translated (after i18n would extract the values) but I am not sure which setting would override which.

**Comment by vangheem** [comment]
Yes. The mockup translations are to translate our JS. pickadate itself has translation strings you can pass in: http://amsul.ca/pickadate.js/date/

**Comment by ichim-david** [comment]
I have added a pull request for plonetheme.barcelonata addressing the styling issue.
https://github.com/plone/plonetheme.barceloneta/pull/44
@vangheem  I will open another pull request for mockups in order to add the translation string directly to the mockup pickdate pattern following your suggestion.

**Comment by ichim-david** [comment]
I have fixed the design issues but what remains is this mockup pull request which I need assistance in making sure that I made the correct change to widgets.pot file in order to get a better translation for the widget labels.
https://github.com/plone/mockup/pull/577

I still think it made more sense to add those strings in plone.app.widgets since they are added directly on the pattern of the widget instead of the body tag like it happens from mockup but I am quite new to the mockup - patterns - widgets combo so I can be quite wrong.

**Comment by pbauer** [comment]
The style-issue is fixed. If you want you an create a new ticket for the translation-discussions.
