### ISSUE TITLE
album view: wild positioning of short names

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#911]
See screenshot
![screenshot-dev1 veit-schiele de 12020 2015-09-10 16-08-05](https://cloud.githubusercontent.com/assets/594239/9790430/42bbe6f6-57d6-11e5-8c3e-6aee8a13f6ba.png)

**Comment by ichim-david** [comment]
Issue fixed in
https://github.com/plone/plonetheme.barceloneta/commit/e5d8d0205e3bf1ff50b167eab87c7809f288c6e3
Here is a screenshot which shows that now the links are placed below the images like sunburst album_view
![fix-911](https://cloud.githubusercontent.com/assets/152852/9799802/28e77826-5812-11e5-9671-5f388e415c31.png)
