### ISSUE TITLE
Maintenance settings: negative values for 'days' allowed

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#937]
It is possible to enter a negative value for "Days of object history to keep after packing "

**Comment by pbauer** [comment]
Again: Why would you want to enter that?

**Comment by hvelarde** [comment]
again: why don't we just add a validator?

**Comment by zopyx** [comment]
Closing this issue is ignorant. Other forms also check for negative values.

**Comment by zopyx** [comment]
If you raise the question "why would one..." then you could throw all validators out of the windows at all.I am starting getting pissed when you close such issues without THINKING.

**Comment by vangheem** [comment]
PR https://github.com/plone/Products.CMFPlone/pull/977

**Comment by pbauer** [comment]
@zopyx The reason why I closed that ticket is that I think it's not worth the effort to add a validator here because you need Manage Portal permission to access this view. With Manage Portal you can delete any tool in the ZMI, thus killing your website much more effectively than by adding a negative value here. Personaly I don't want to spend my time on such code, but I also should not try to discourage you from adding such validators.

**Comment by vangheem** [comment]
Discussion: https://community.plone.org/t/why-do-we-validate-form-fields/948
