### ISSUE TITLE
Weird widget used to activate comments on item

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#944]
Allow comments widget displays a drop down list with Empty, Yes and No values; this should be just a check box as it was always been:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9816375/f454c0d0-5872-11e5-8e48-57130a09094c.png)

**Comment by davilima6** [comment]
In English that would be "No value" and I think this option shouldn't be there in @@site-controlpanel select boxes as well.

**Comment by davisagli** [comment]
IIRC a value of None here means inherit the value from the parent. Which is a useful setting, but we should label it better!

**Comment by hvelarde** [comment]
@davisagli well, that's new then; that's not the way it works in Plone 4.

**Comment by davisagli** [comment]
It's worked that way in Dexterity ever since plone.app.discussion was around. Plone 4 used Archetypes.

**Comment by ichim-david** [comment]
@davisagli  I don't know if it's not too late with such a change because of translation strings and if there is such a message already but it makes sense then to simply rename  None to "Inherited from parent".

**Comment by pbauer** [comment]
The widget is ok like this but pretty confusing. For details see https://github.com/plone/Products.CMFPlone/issues/972

**Comment by tisto** [comment]
This has been on my todo list for quite a while. I agree that the current labels are confusing. We should at least rename "none" to "inherit the value from parent". Though, going back to checkboxes is not an option since this means the "inherit" setting is the initial setting that can never be reached again after choosing yes/no. The way Plone 3 implements this does not make any sense at all.
