### ISSUE TITLE
More… menu completely misplaced

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#952]
When you select the More… menu it is shown far right.

With the tollbar collapsed:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9818224/c29b96ee-587d-11e5-9875-2897f2f88708.png)

With the toolbar expanded:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9818225/c2a1e01c-587d-11e5-93fb-8f9f15f62c79.png)

**Comment by vangheem** [comment]
Would you please consolidate all horizontal menu related issues into one ticket?

**Comment by hvelarde** [comment]
would you prefer that? for me is easier to have one ticket for issue, but let me know.

meanwhile I will open a new issue with a check list.

**Comment by ichim-david** [comment]
I have found out the reason for this although I am not familiar with the code and I don't have a fix.
it because of duplicated links that are outside of the list items
Look at the inspector and see that we have copy link which should be only visible when clicking the actions menu
![duplicated-markup-visible](https://cloud.githubusercontent.com/assets/152852/9824150/bb66d5fe-58d3-11e5-8c10-4fdff7cf1f9f.png)

If i hide all of the extra links look how nice the second toolbar looks even when clicking on the actions 
![duplicated-markup](https://cloud.githubusercontent.com/assets/152852/9824168/d0114e6c-58d3-11e5-898c-ecdf838b5c13.png)

@hvelarde  @vangheem  the links are duplicated with the same id at least 2 types. If the duplication stops I believe that this issue will be fixed.

If I have time tomorrow I will try to study how this toolbar works at it changes at different visual breakpoints
