### ISSUE TITLE
Folder contents option displayed on non-contentish objects

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#953]
When you are in the context of a non-contentish object (an item, not a folder), you shouldn't be able to see Folder contents option:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9818902/2c8149c0-5881-11e5-8f7f-40e1312b96f0.png)

**Comment by vangheem** [comment]
Showing it all the time was on purpose.

**Comment by vangheem** [comment]
We want users to always be able to manage contents. Otherwise, you need up go up to the folder and then click on "contents".

**Comment by davilima6** [comment]
Agree, it's a valuable shortcut for frequent task flow and besides it shouldn't confuse users since it's there all the time. Maybe we could have a title: "Current folder contents", like other toolbar buttons.

Besides I also vote for transforming those titles into tooltips, in the same fashion as folder contents buttons. They're more visible and the lack of delay makes them best suited to our needs imo.
