### ISSUE TITLE
Icon visibility not being obeyed

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#963]
If I set icon visibility to *Never* in Site Settings configlet:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9824592/2db1930e-58a4-11e5-86ae-2da0684cbbb8.png)

Icons are still visible all over the place:

![selection_005](https://cloud.githubusercontent.com/assets/341393/9824593/2dba6a10-58a4-11e5-962f-148fad76fff9.png)

![selection_004](https://cloud.githubusercontent.com/assets/341393/9824647/9e2b6f9c-58a4-11e5-90b9-898669db7129.png)

**Comment by vangheem** [comment]
Icon visibility never applied to admin UI. Only the 3rd screenshot here matters.

**Comment by davilima6** [comment]
Actually I checked and they did apply to admin ui. IIRC native content-types get their icons omitted when this option is turned off since at least Plone 2.5.

**Comment by vangheem** [comment]
I wish we would have deprecated this... With all the icon fonts we use, how do you actually even implement this anymore? What about icon-only mode for toolbar? Does this mean icons are gone in control panel too?

I guess some potentially really annoying css rules. This should just be a theme thing...

**Comment by davilima6** [comment]
I agree it makes much more sense to hide icons from visitors than from logged-in users since the graphics might remind one more of the Plone brand than the site's. I wouldn't mind if that was dropped/deprecated. I don't think this option should impact the toolbar or control panel icons. Actually the form help from Plone 4 is missing: `If disabled the content icons in folder listings and portlets won't be visible.`

Regarding icon fonts for content-types, I agree it should be a goal (even hough GenericSetup still expects images). Maybe Plone could even have its own icon font in order to keep a bit of personality across other generic icon font based applications and also to depend less on sprites.

**Comment by hvelarde** [comment]
@vangheem don't remove this: there are hundreds of sites that use it.

FYI @jeanferri

**Comment by vangheem** [comment]
That's fine. If we can just agree that we target only public related stuff I don't think it'd be too difficult creating rules that apply this.

**Comment by vangheem** [comment]
https://github.com/plone/Products.CMFPlone/pull/976

One problem here is that through all the alphas, betas, RC, icon visibility defaults to "false" which is the actual setting on those sites now. Adding this will change the way those sites look.

Because of that and because of obvious usability reasons, this PR attempts to not hide icons for admin functions. It was a mistake to ever remove icons for admin functions.

**Comment by vangheem** [comment]
Closed: https://github.com/plone/Products.CMFPlone/pull/976
