### ISSUE TITLE
Why there's no workflow for "File" and "Image" content types?

### ISSUE THREAD

**Issue by idgserpro** [plone/Products.CMFPlone#964]
I know they don't [have workflow](http://docs.plone.org/develop/plone/content/workflow.html#disabling-workflow-for-a-content-type), but what's exactly the motivation of this peculiarity? Historical reasons? Usability perspective?

They don't have versioning too, is this related to not having workflow? People that use history view for example for all types and upload a lot of Microsoft Office documents to Plone won't have this this feature unless they set versioning behavior and some [ugly workarounds](https://github.com/plone/plone.app.versioningbehavior/issues/14#issuecomment-104269834).

I'm posting this here because this behavior comes from Archetypes and Dexterity.

**Comment by ableeb** [comment]
IIRC this is legacy, in that the thinking was that Files and Images should immediately be available upon upload.

**Comment by cewing** [comment]
I believe the original choice was made to avoid a very common user error where a link from a published document to an unpublished file (or the addition of an unpublished image to a rich-text field in a published document) would cause access errors.

**Comment by idgserpro** [comment]
I think I mixed two subjects: workflow and versioning for history view, I've edited to question to make it clearer.

**Comment by cewing** [comment]
I think the lack of versioning is due to complexities around versioning blob data.  I am not certain of this, though.

**Comment by idgserpro** [comment]
@cewing Using [workarounds](https://github.com/plone/plone.app.versioningbehavior/issues/14#issuecomment-104269834) versioning of blob works. Would it be the case to make versioning default for everybody in the future versions after reviewing it?

I'm not complaining, I just would like to know the motivations and technical problems specially because users keep asking "why these two content types can't be the same as the others" and I'm not a fan of saying "it's just the way that Plone works". I think all these motivations could be added to the official docs.

**Comment by hvelarde** [comment]
@idgserpro you can change the default configuration if that's the case; the workflow decision was because of usability issues as @cewing explained before.

**Comment by cewing** [comment]
I'm not sure I'd be in favor of making it the default behavior.  Blobs can be quite big, and versioning them by default opens the door to exhausting disk space for users without there being an obvious reason why.

**Comment by do3cc** [comment]
CMFEditions has a handler for blobs when a version gets stored. If the blob is unchanged, it manages not to create a copy of the blob

**Comment by polyester** [comment]
It was usability reasons; especially for images (too many cases where people published pages which then had 'gaps' due to unpublished images). The standard behaviour was therefore changed so they inherited their container permissions.

I still think this is a good default setting for sites with mainly images and 'public docs' like PDF's; I've made effort in the Plone5 docs (working on them this weekend like a madman) to explain how to change that for files and/or images.

**Comment by jensens** [comment]
we may want to change this if we start to make documents folderish, at least its worth a discussion, see plone/plone.app.contenttypes#196

**Comment by tkimnguyen** [comment]
*plug* castlecms.io re-enabled workflow for File and Image types but also has a content quality check before publishing that checks if any linked-to items on the site (internal links) are unpublished

**Comment by gforcada** [comment]
@tkimnguyen this content quality check would be really useful to have in Plone by itself, the workflows on File and Image are probably worth a separate PLIP, so would you PLIP the quality check? :-)

**Comment by tkimnguyen** [comment]
@gforcada @jensens I went looking for how to create a PLIP (that won't be closed by *cough*Jens*cough*) and found that http://docs.plone.org/develop/coredev/docs/plips.html#how-submit-plip has a broken link to http://issuetemplate.com/#/plone/Products.CMFPlone/PLIP

**Comment by hvelarde** [comment]
I think a PLIP on changing the workflow for FIle and Image is unnecessary and must be avoided; as @polyester said, documentation on how to change it is good enough.

**Comment by idgserpro** [comment]
>  versioning is complex stuff and it has many issues that will make a newbie completely mad.

We're not so sure about adding it either, but from an usability perspective, we don't know the best way (even *where* to say it) to inform the person using the platform that these specific types don't have versioning. Anyone has any idea if we can improve this somehow?

> curiously I'm currently cleaning a site with orphan histories and content types with more that 1.000 versions on their instances.

We opened this issue because a client complained the complete opposite, "why don't we have history for file and images since all items have it?" :laughing: 

Anyways, I think the idea here from @tkimnguyen is about adding workflow, not versioning.

**Comment by tkimnguyen** [comment]
I think there are a few things going on here!

- I think if someone wants to discuss adding versioning by default to File and Image types, that should be a separate issue or PLIP

- If the discussion in this issue is about whether to restore a workflow for File and Image types, the reason why they don't currently have their own state is NOT a problem anymore if we include a quality content check like the one in Castle, and @gforcada was suggesting I PLIP that quality content check. A simple enough way to alert users to the inherited state for File and Image types is to display an info/warning, e.g. "This file is currently visible to the public (It has inherited the state of its parent folder)" or something similar.

- My question about how to PLIP is a general one, because the process (in my mind, anyway) has changed a few times in the last few years, and I'd like to know what it is now :)

**Comment by thet** [comment]
@tkimnguyen tnx for pointing out the problem with the PLIP issue template: https://github.com/plone/Products.CMFPlone/issues/1891
Basically, this is a good PLIP example: https://github.com/plone/Products.CMFPlone/issues/1343

**Comment by jensens** [comment]
OT but FYI: I created a PLIP for a issue template at #1893

**Comment by tkimnguyen** [comment]
I started the PLIP https://github.com/plone/Products.CMFPlone/issues/1894 for adding a quality content check feature. Please jump in if you're interested :)

**Comment by tkimnguyen** [comment]
Rereading the comments above, I think we can close this issue because we have answered the question "why is there no workflow for File and Image types?". If someone wants to pursue another possible solution, please create a new issue. (e.g. if File and Image types do not have their own workflow state, have an Info message appear if the File or Image is or isn't publicly visible based on its container).
