### ISSUE TITLE
Last modification date button is redundant on the toolbar

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#999]
Now that we have back in place the document_byline viewlet, the information provided by the last modification button on the toolbar became useless.

![selection_004](https://cloud.githubusercontent.com/assets/341393/9909987/23f29342-5c71-11e5-96bd-12c94d39d128.png)

We can remove it so we can get more space for other options.

**Comment by davisagli** [comment]
Not useless. It's there because not every site will choose to keep the byline enabled.

**Comment by hvelarde** [comment]
you can always leave the byline enabled for authenticated users and then that button is redundant; besides that, the viewlet gives you way more information than the button: you can see who created the item, when was created and when it was modified.

**Comment by polyester** [comment]
Indeed not useless. The premise behind the toolbar is: 
- whatever crazy diazo theme you decide to use, all information relevant to editors is available through the toolbar.

Now you've (succesfully) argued that the byline is dual-purpose: it can be useful to editors but also visitors. So in those cases it will indeed appear twice. Others are free to not show the viewlet; I will certainly disable it as having appear things inside the content area that look different when logged in as opposed to not-logged-in was confusing to some users.

**Comment by davilima6** [comment]
I think the viewlet could come disabled by default so we don't showcase ootb a repetitive UI.

**Comment by hvelarde** [comment]
the problem, @polyester, is that the bar fails on your premise: using the toolbar I'm not able to know who created the item and when it was created (or modified); it only displays an icon (on collapsed mode) that I have to hover on to see just part of the information that was previously available:

![selection_004](https://cloud.githubusercontent.com/assets/341393/9914172/e505b1d0-5c86-11e5-9907-f98238429cf6.png)

guys, the bar is broken in many aspects and I've been saying the obvious for months now: we decided to change a perfectly usable UI for a broken one, that's the sad true; we better fix it quickly.

@davilima6 no, we need to fix the toolbar first.

**Comment by polyester** [comment]
We indeed disagree, especially if you think Plone 4 had a 'perfectly usable UI'. And you have indeed been saying the same for months, only you call it "the obvious" whereas for me it is "hvelarde's viewpoint" which is different from my viewpoint, my usecases, and my idea on how a UI should behave in a future with multiple frontends talking to the same backend; some of which may not even have 'viewlets' to enable.
Your obvious may not be other people's obvious. And yes, it is hard to please everybody all the time. And yes, there is room for evolving the toolbar.

 Yet, putting back editor-info like a 'history' link into a viewlet as the *only* option of getting to it, is limiting everybody else's possibilities to your usecase. For me, it leads straight back in 'green bar syndrome', the mixing of two things that should not be mixed.

**Comment by hvelarde** [comment]
I disagree, Paul; the "obvious" here is the toolbar doesn't give "all information relevant to editors"; that's not my point of view, but a fact.

the problem is we remove things all over the place without the proper care of having a working alternate solution; I've been repeating this for months and the only argument I read is: "but... but... the toolbar is so cool".

now you came with some valid points; great, that's what we needed from the beginning. 

I have to get back to work now; I've spent way too much time opening issues in the previous days.

for now, I'm done.

**Comment by djay** [comment]
+100

**Comment by thet** [comment]
I'd change the byline viewlet:
- Remove the "History" link, because that will only be shown to users with appropriate permissions, who will have the toolbar also visible. 
- Change "last modification" to "created on", because IMO, thats more relevant for users in most use cases.
- Use moment.js pattern on the viewlet's "created" on date.

**Comment by davisagli** [comment]
> Change "last modification" to "created on", because IMO, thats more relevant for users in most use cases.

Both are relevant, in my opinion.

**Comment by thet** [comment]
I agree - depending on the usecase. Best would be to have that configurable, which one to show.

**Comment by jcerjak** [comment]
I strongly agree with @polyester - all information that is relevant to the editors should be available in the toolbar. 

Reasons:
* Versioning is a strong and very useful feature, IMHO it would be weird if it wasn't accessible from the toolbar.
* Integrating the document_byline viewlet in the theme doesn't work for all themes
* One place where all the editing is happening, instead of having to visually scan the page for the admin functionality (which a lot of our users found confusing in Plone < 5). We moved most of the edit functionality (including manage portlets etc.) to the toolbar, why not this?

I agree that it would be very useful to have the author info also in the toolbar. Is there room in the UI to include it, at least for expanded mode? Otherwise I think the current situation with the viewlet AND the menu entry in the toolbar is an acceptable compromise.

**Comment by hvelarde** [comment]
I also agree with @polyester: the information should be there, but is not; byline viewlet must be in place by default:

https://twitter.com/hvelarde/status/622045162542383104

if someone doesn't want it in a theme, can easily remove it with one Diazo line.

**Comment by hvelarde** [comment]
superseded by #1560
